### ISSUE TITLE
Add ability to download xml file from http location

### ISSUE THREAD

**Issue by belingueres** [revelc/formatter-maven-plugin#103]
I want to share the same formating rules between all projects. A useful feature would be to get the xml file from a single location or URL (or maybe a maven repo?). This way I could add the same configuration in a corporate pom shared between all my projects.

TIA,
Gabriel

**Comment by ctubbsii** [comment]
Rather than bake this feature in, I think it'd be preferable to download the file in a previous point in the lifecycle, before running the plugin. [Here's an example on StackOverflow for how to do it.][1]

[1]: http://stackoverflow.com/questions/2741806/maven-downloading-files-from-url
