### ISSUE TITLE
Check formatting but not modify the files

### ISSUE THREAD

**Issue by sgandon** [revelc/formatter-maven-plugin#108]
Hello,
I need to have the maven build (run from a Jenkins) to check for the formatting and stops the build is one or more files are not compliant to a given eclipse formatting.
I don't want to actually modify the files as I am on the jenkins server.
Because there is not way to force developers to use maven build before committing anything, it would be great to simply have a check and not format anything.

**Comment by sgandon** [comment]
Ok I guess the ValidateMojo is doing this very precise thing but it is not mentionned in the current release available on maven central : 0.5.2.

**Comment by ctubbsii** [comment]
It's not even mentioned in the goals at http://code.revelc.net/formatter-maven-plugin/plugin-info.html for 0.5.3-SNAPSHOT.

We probably need to do another release soon, with MARS formatter support and the validate goal documented.

**Comment by sgandon** [comment]
can you let me know where (which maven repo) can I get the 0.5.3-SNAPSHOT please ?

**Comment by ctubbsii** [comment]
SNAPSHOT refers to a local build. I'm not sure where, if anywhere, anybody has published that version, but it's not necessarily a tested release. You can check out the source code today, and build the master branch, which I think is version 1.6.0-SNAPSHOT (versioning here is funky, due to merging separately-versioned forks).

**Comment by velo** [comment]
You can use my fork...

http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.marvinformatics.formatter%22%20AND%20a%3A%22formatter-maven-plugin%22

That functionality came from it anyway

**Comment by sgandon** [comment]
Thanks very much but whater artifact I use I keep getting the same error 
`[ERROR] Failed to execute goal com.marvinformatics.formatter:formatter-maven-plugin:1.6.0.RC4:validate (default) on project daikon-parent: Execution default of goal com.marvinformatics.formatter:formatter-maven-plugin:1.6.0.RC4:validate failed: Plugin com.marvinformatics.formatter:formatter-maven-plugin:1.6.0.RC4 or one of its dependencies could not be resolved: Failed to collect dependencies at com.marvinformatics.formatter:formatter-maven-plugin:jar:1.6.0.RC4 -> org.talend.tools:java-formatter:jar:0.1.0-SNAPSHOT: Failed to read artifact descriptor for org.talend.tools:java-formatter:jar:0.1.0-SNAPSHOT: Could not transfer artifact org.talend.tools:java-formatter:pom:0.1.0-SNAPSHOT from/to m2e-core (https://otto.takari.io/content/sites/m2e.extras/m2e/1.6.0/N/LATEST): Cannot access https://otto.takari.io/content/sites/m2e.extras/m2e/1.6.0/N/LATEST with type p2 using the available connector factories: BasicRepositoryConnectorFactory: Cannot access https://otto.takari.io/content/sites/m2e.extras/m2e/1.6.0/N/LATEST with type p2 using the available layout factories: Maven2RepositoryLayoutFactory: Unsupported repository layout p2 -> [Help 1]`
I am a bit disapointed.

**Comment by ctubbsii** [comment]
I would like to get a new release soon which would include these features, but I've been taking a look at the build, and it's a bit confusing to me... not at all what I'm used to for a maven project. Some of the things that confuse me are:

1. the Eclipse plugin modules,
1. the dependency on repos other than what's in Maven Central,
1. the tanaki parent pom,
1. the proguard plugin, and
1. the specialized maven extension for staging a release candidate

**Comment by hazendaz** [comment]
@ctubbsii Separately I think we should just split the library into a copy of repos as we are mainly concerned on the formatting here.  The eclipse piece which we still have a learning curve on it shouldn't release more than 3 times a year based on eclipse schedule and we can configure that such that it releases as needed.

As for questions here on CI type formatting to stop builds, that is now released so closing this ticket.
