### ISSUE TITLE
AppVoyer issues

### ISSUE THREAD

**Issue by hazendaz** [revelc/formatter-maven-plugin#113]
Appvoyer is very unstable.  It's working but fails to download things quite a bit.  When it does properly work, our builds are completely successful.

**Comment by ctubbsii** [comment]
The travis-ci builds seem stable enough. Do we really need both?

**Comment by velo** [comment]
travis run on linux/mac
appveyor runs on windows

I remember having problems with this plugin the very first try I ran on windows....  today I don't know any isses, but is a matter of preventing those.

**Comment by ctubbsii** [comment]
Oh, I see. I guess it's useful to ensure Windows builds work, then.

**Comment by hazendaz** [comment]
The build in appvoyer is working now.  What I'm seeing though is that it fails on many occassions to download various dependencies.  The one I saw most was the license plugin.  It stated it was not available yet trying again it just worked.  So I find it a bit unstable. And at the very least wanted a note out here regarding that in case we continue to see this.

Now ironically after recent update to make it include all files that should have license headers to auto apply, app voyer was getting one file checked out that the license header applied 2016 date on it.  Neither local windows for me or travis had the same issue.  The quick fix was to simply upgrade the year on that single file and the error in question then happened on my machine as well so I updated the sha for the file.  I haven't seen this occur before but most projects just use travis-ci unless there was some specific reason to use windows (ie .net).  I don't see any real specific reason to use windows here other than to vet out the line endings issues.  Other than that I don't think it's at all important to have given the stability.  It seems to me this is a lot like cloudbees.  That one (jenkins) is really unstable as well.  From the way I see it, travis ci is significantly more stable.

**Comment by hazendaz** [comment]
One other strange thing.  On appvoyer, I kicked it off manually and the last build 51 is fine but that doesn't reflect on our project.

https://ci.appveyor.com/project/hazendaz/formatter-maven-plugin/build/51

**Comment by hazendaz** [comment]
Appvoyer is failing again.  Looks like they might have changed maven M2_HOME variable location.

**Comment by hazendaz** [comment]
Build is working fine now, closing this.
