### ISSUE TITLE
Default to overriding the config file compiler versions

### ISSUE THREAD

**Issue by GoogleCodeExporter** [revelc/formatter-maven-plugin#14]
```
Avoid needing to specify a parameter to override the compiler versions in the 
config file.

If the values are explicitly set, use them instead of the config file versions.
If the values are not set, use those in the config file.
If none are defined in the config file or the config file is unspecified, use 
the default (1.5)

Remove the override config file parameter, as it would be unnecessary.
```

Original issue reported on code.google.com by `matt.blanchette@gmail.com` on 1 Mar 2011 at 8:25

**Comment by hazendaz** [comment]
I believe this is complete -> @Parameter(defaultValue = "1.5", property = "maven.compiler.source").  I believe that uses 1.5 unless the maven.compiler.source is set.  That means, even if user doesn't set it, it will use 1.5 as that is current maven default.  In 3.3.x, the default is 1.7 now I believe.
