### ISSUE TITLE
Maven Central

### ISSUE THREAD

**Issue by mwensveen-nl** [revelc/formatter-maven-plugin#142]
Hi, 
Is there any change that the latest release (2.0.0) is going to be available in de maven central repository. At this moment 0.5.2 is the latest available.

**Comment by hazendaz** [comment]
Ill try to get a release out very shortly (maybe today).  I was told javascript formatting isnt working so ill take a look at that first.

Get Outlook for Android<https://aka.ms/ghei36>



On Mon, Nov 28, 2016 at 6:01 AM -0500, "mwensveen-nl" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,
Is there any change that the latest release (2.0.0) is going to be available in de maven central repository. At this moment 0.5.2 is the latest available.

**Comment by mkopec87** [comment]
Hi, any update on this? :)

**Comment by ctubbsii** [comment]
@mkopec87  We had some discussion of the release process on #149 , which I think has made some progress. I'm sure you can expect a release soon.

**Comment by hazendaz** [comment]
@mkopec87 I pushed a manual release.  It should be in central in next couple of hours as version 2.0.0.  Everything is pushed to central so typical m2e if needed probably isn't ready to go but from a standalone build perspective, it should be good enough.  I'll leave this open until I hear back that it's working as expected.  Thanks.

**Comment by hazendaz** [comment]
I personally verified on another project this is uploaded now.  Now the search maven central is under maintenance and quite backed up.  I'm told another day or so before it shows there but it does work.  Keep in mind the groupId added '.formatter' and version is 2.0.0 to use.
