### ISSUE TITLE
How to release????

### ISSUE THREAD

**Issue by hazendaz** [revelc/formatter-maven-plugin#149]
[INFO] [ERROR] Failed to execute goal org.eclipse.tycho:tycho-packaging-plugin:0.24.0:validate-version (default-validate-version) on project jdt-core: Maven version 2.0.0 must have -SNAPSHOT qualifier for SNAPSHOT builds

So trying to push release 2.0.0, besides a very messy package setup that I'll fix later (ie it asked me more than the typical once for version number), I cannot get through release:prepare.  It fails with the error above.  Any ideas?

**Comment by ctubbsii** [comment]
Which branch/commit are you trying to release from?
(Side-note: seems we have a lot of extra branches, which probably need to be cleaned up... not sure what all those are about.)

The multiple prompts was probably because we don't have `autoVersionSubmodules` set to `true`.

**Comment by hazendaz** [comment]
Ah yah...that probably isnt set.  Ill check tonight.

I was trying to run release off master.

All the branches are currently needed.  Its using tycho to get eclipse mars.  I dont understand much about that but do know the next parent blocks the compiler plugin and says we must use a different lifecycle.  Thst could have something to do with it.

Get Outlook for Android<https://aka.ms/ghei36>



On Tue, Nov 29, 2016 at 12:37 AM -0500, "Christopher Tubbs" <notifications@github.com<mailto:notifications@github.com>> wrote:


Which branch/commit are you trying to release from?
(Side-note: seems we have a lot of extra branches, which probably need to be cleaned up... not sure what all those are about.)

The multiple prompts was probably because we don't have autoVersionSubmodules set to true.

-

**Comment by ctubbsii** [comment]
I looked into this, and it appears that the problem is with https://www.eclipse.org/tycho/sitedocs/tycho-packaging-plugin/validate-version-mojo.html

There are a few places in the code where "1.6.0.qualifier" is hard-coded. `grep -R qualifier .`
This causes a mismatch with the OSGi and Maven versions for a release version.

**Comment by ctubbsii** [comment]
I have a fix for the release in #150 . However, it will probably fail on the next snapshot. We should do something to generate the OSGi version properties using property interpolation with the maven-resources-plugin.

**Comment by ctubbsii** [comment]
I noticed that we're still using Java 7. I think we should bump to requiring Java 8.

**Comment by velo** [comment]
this is how I release it:
https://github.com/velo/maven-formatter-plugin/issues/18

**Comment by hazendaz** [comment]
Thanks @velo.  Not sure I fully understand why it's done that way and why the versions in the files are not being updated on the source repo like release plugin does.  For the time being as that is a lot to learn/understand, I'll go the old fashioned way.

@ctubbsii..I think that is why I was using 0.24.0 of tycho.  Should be fine otherwise other than possible breaking travis build.  It's downcast to java 7 so should be good to go.  After release, if nothing major comes in being reported, we can go forward with java 8 and update to neon as well.

**Comment by velo** [comment]
Ow, I do my best to stay away from maven-release-plugin

**Comment by ctubbsii** [comment]
I've been really happy with the maven-release-plugin and git, as long as autoVersionSubmodules is true, pushChanges is false, and localCheckout is true. It really helps automate things according to Maven conventions, and works well with pushing to a staging repository like Maven Central.

This plugin is by far, one of the most complicated ones I've seen. I'm still not sure how much of that is due to the Eclipse OSGi stuff and necessary, or how much is due to Maven messiness which can be cleaned up incrementally. I wonder if this could be simplified if we separated the build of the Eclipse plugin from the maven plugin a bit. Or, maybe things will just get better over time if the Eclipse community starts doing more with Maven.

**Comment by hazendaz** [comment]
Same feelings here.  I tried the release.  It only would push a small portion.  I must admit I don't understand tycho or why we need it across everything.  I understand for portions it's certainly needed from the looks of it as it grabs the eclipse bundles.  However, those even run on mvn clean which is concerning.  I think splitting it into two makes sense or it might be a bit longer to fully understand tycho and what it's all about.  I know if we upgrade to latest tycho (0.17.0, 1.1.0 was a bad release), it won't even run the compiler plugin and states we are not allowed to do so.  I really don't understand why it stands to want to break everything from working well.  I'm sure there is some reason but this is certainly very complex build as a result.

**Comment by velo** [comment]
> This plugin is by far, one of the most complicated ones I've seen.
Indeed.
That is the main reason why I automated the release with rultor... now releases take zero effort =)

**Comment by hazendaz** [comment]
Re-opening as release failed using maven release as it skips all the deployments due to tycho.

**Comment by velo** [comment]
>  I must admit I don't understand tycho or why we need it across everything

tycho bridges maven and eclipse worlds...
I use tycho do grab eclipse jdt-core and pack in a maven usable way

**Comment by hazendaz** [comment]
So would it make sense then to split it?  The normal plugin doesn't require the eclipse world technically speaking.  So maybe run just what needs run to perform the eclipse builds.  Keep in mind eclipse is only going to release 3 cuts of each version of Eclipse anyways.  So our need to constantly build that piece which fails way to often isn't that necessary.

**Comment by velo** [comment]
wait, what?
The maven plugin uses jdt-core... what do you mean by "normal plugin doesn't require the eclipse world"?

This plugin runs eclipse jdt-core to make formatting happen.

**Comment by hazendaz** [comment]
What I mean is that can be built separately.  We could even just use your builds of that piece and ignore building it here.  We didn't have the original this tightly integrated and the largest complaint/concern I've seen about the current code is that the eclipse site piece fails all the time.  And that much is pretty valid.  It failed on me twice tonight.  There are also only three releases of Mars (first, patch 1, patch 2).  Same thing every year.  It's dated as much in the build output.  So I don't understand why every last build must go do that again.  It seems like overwork for no real valid reason.  Then it goes as far as using proguard which I don't think is appropriate.  Why are we obcuring eclipses open source code?  I don't see the point.  At the end of the day I just want all my code bases formatted in a common way but really don't care how closely bundled I am to any specific formatting solution.

**Comment by hazendaz** [comment]
Any way...logging off for the night.  Talk to you guys later ;)

**Comment by velo** [comment]
>  We didn't have the original this tightly integrated

Indeed... but the original plugin was not able to upgrade eclipse at will... it would need to wait for it to appear on maven central... which could take a while if happening at all.

> There are also only three releases of Mars (first, patch 1, patch 2). Same thing every year. It's dated as much in the build output. So I don't understand why every last build must go do that again. 

sure, you can have one project deploying the eclipse jdt-core and another just for this plugin, but currently, eclipse releases happen way more often the formatter-plugin releases. 

> Why are we obcuring eclipses open source code?

We are not, I just shrink the jar so it only include the classes I need... not half eclipse.

**Comment by hazendaz** [comment]
We are not, I just shrink the jar so it only include the classes I need... not half eclipse. --> Gotcha!

**Comment by ctubbsii** [comment]
> Indeed... but the original plugin was not able to upgrade eclipse at will... it would need to wait for it to appear on maven central... which could take a while if happening at all.

Yes, it's too bad Eclipse doesn't do this automatically.

> currently, eclipse releases happen way more often the formatter-plugin releases.

I would be helping out a lot more, if things weren't so complex. I know Maven, but I don't know Eclipse. This project seems to require a lot more understanding of Eclipse than it does Maven. This isn't necessarily a problem with the project, but I do wish I understood more about how it could be simplified.

**Comment by velo** [comment]
If you mvn clean install all, then you can import only the maven plugin at
your ide and play along.

Releasing is already fully automated on my fork, cherry pick it and be
happy :)

**Comment by ctubbsii** [comment]
For reference, https://bugs.eclipse.org/bugs/show_bug.cgi?id=484004

**Comment by hazendaz** [comment]
I manually uploaded the release.  Still don't understand why tycho likes to stop plugin usage.  Seems pointless.  The artifacts all create fine on a build so just released everything that way to central.  I'm sure that misses something for m2e as a result as I just released all that to central as well.  However, I think those that care are not caring much about m2e integration as they are just running the plugin.  So at least it's partially complete.  Should be up there in a few hours...

**Comment by velo** [comment]
Well, the steps I use to release using rultor work just fine... embrace it.

**Comment by hazendaz** [comment]
Id rather split this into two pieces to clearly separate the eclipse vs maven plugin first.  At that time id be able to learn the tool you use.  Otherwise extremely limited on time and formatting needs are not really a priority.  Splitting into two makes most sense but obviously not a good time to make such a change to get released.

Maybe you could help with that?  I feel our plugin is more likely to get released more frequently that way especially as it learns new formatting and our internal code improves.

For now im just trying to push out the door for various users asking and corporate needs.  That much makes it good enough for now.

Anyway still keeping new learning on the back of my mind :)

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hazendaz** [comment]
Opened #154 to separate out eclipse only vs standard maven plugin.  Release ended up being completely manual in current case as we don't have rultor setup.  Rultor can be used on eclipse side of the house but for standard side I'd prefer we stick to maven-release-plugin as it works.
