### ISSUE TITLE
Separate Eclipse pieces vs Maven Plugin

### ISSUE THREAD

**Issue by hazendaz** [revelc/formatter-maven-plugin#154]
As eclipse piece requires tycho which the maven plugin pieces does not, releases are far too complicated.  While @velo has a special plugin, I feel that doesn't properly adhere to normal release practices in github.  So since it's clear the tycho piece is for eclipse only and the plugin itself doesn't care, we need to separate the two apart.  The expectation is the eclipse piece will release each time eclipse makes a release.  On the flipside, our plugin will then be more easily released and support new features since that is our core code anyways.

**Comment by velo** [comment]
Maven plugin does use tycho to grab jdt and jsdt

**Comment by hazendaz** [comment]
No. formatter-maven-plugin itself does not.  It uses the dependencies only.  All the other pieces should be completely separated.  Only those pieces need tycho.

Separation would be this.

formatters, m2e-configuration go into their own project (ie the Eclipse needed project until eclipse more actively releases to central with this eventually being dropped).
maven-plugin -> stays in current project.

The maven plugins only use on eclipse is for these two dependencies.  Tycho is not needed to retrieve those, maven central is.  It wasn't before we merged these code bases and still no reason.  It's simply using the built dependencies here which it can get from central.  Those will be in the other repo and released to central with the project not changing in this piece other than it will no longer call super pom of tycho.

```
        <dependency>
            <groupId>net.revelc.code.formatter</groupId>
            <artifactId>jdt-core</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>net.revelc.code.formatter</groupId>
            <artifactId>jsdt-core</artifactId>
            <version>${project.version}</version>
        </dependency>
```
I'll task myself the work on this.  It's trivial and probably takes no more than a couple of hours to break.  No code changes necessary and all group/id folder structure will remain.  The upper parent of this project will adjust a bit but that is about it.  Then we get the ease to release using standard release on the piece that matters the most to us.

**Comment by velo** [comment]
Considering latest eclipse is 4.7 (oxygen) this seems really out-to-date

**Comment by hazendaz** [comment]
oxygen isn't released until June 2017.  Milestone releases are far too early to even be considering.  Only hard-core developers that are willing to take risk use those releases.  That would be like us requiring java 9 to compile this.  It's not ready and therefore shouldn't be in the discussion.

You have to keep in mind this product is being used in corporate environments.  Those corporate environments, even the best of them, are still on Mars, if there at all.  I'm all about supporting new things but certainly not beta releases.  And yes, I have used oxygen but switched back to neon as it didn't provide anything at all I needed.

**Comment by velo** [comment]
Fair point... neon 4.6....  that ain't beta anymore

**Comment by ctubbsii** [comment]
While it may still be worth separating the Eclipse plugin from the Maven plugin, there is some ongoing effort within the Eclipse community (https://bugs.eclipse.org/bugs/show_bug.cgi?id=484004) to make the JDT and other core Eclipse artifacts available in Maven Central. This could simplify things for downstream projects like this one which don't necessarily need the OSGi bits, and could get away with a simpler Maven build, without using Tycho.

I would recommend following the progress of that work, to see how it might affect us (or how we can take advantage of it).

**Comment by velo** [comment]
Well, the target version for it is 4.7

Which won't cut for this mars requirement Jeremy mention

**Comment by hazendaz** [comment]
Mar cut is released now so mars is done.  Only Neon is left for us to do.  I'd suffer through the manual release again.  It only took an hour or two ;)  However, for now, at least on my part, I'm considering this done for a while and will be working to get the mars cut into corporate use (these days means lots of extra work not just using it).  I've gotten it into two open source already.  So will be at least two to three months before I have it completely spread through corporate needs.  At that point, fingers crossed neon will have more corporate use approval and as such will be a good point to complete that.  At least that is where I stand on this.  In the old days before XX vulnerabilties started flying everywhere, it use to be nothing to release and use widespread same day.  These days these things take months.

**Comment by velo** [comment]
Well, I released mine with neon... it's a trivial process using rultor, I
still don't understand why you guys don't do the exact same thing and move
on

**Comment by ctubbsii** [comment]
If rultor is the most sensible thing to do, that's fine. I'm not familiar with it at all, and the release process using that is not documented anywhere within the project itself. But, the project does have maven-release-plugin configured... and it's a maven project, so it *looks* like that's the expectation, since that's the standard and there is an absence of alternative instructions.

**Comment by hazendaz** [comment]
For me its lack of time to learn it.  Thats all.  More of my time is deep in learning spring java config and boot.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hazendaz** [comment]
tycho does release to central the jdt-core.  Bits and pieces of jfaces/text are out there separately but not all the way up-to-date and jsdt is missing entirely at current.

```
        <dependency>
            <groupId>org.eclipse.tycho</groupId>
            <artifactId>org.eclipse.jdt.core</artifactId>
            <version>3.12.2.v20161117-1814</version>
        </dependency>
```

**Comment by hazendaz** [comment]
Neon.2 is otherwise live now.

**Comment by hazendaz** [comment]
Most likely related to having maven mixed with takari, poms for various pieces (m2e in this case) have not been created since february and travis ci cannot see them on further updates to get to neon.

**Comment by hazendaz** [comment]
To add to my last comment, various .pom files are showing up with february dates while everything else is new.  This was causing build failures on travis.  However, attempting to do again today after about a month, all seems well now so pushing that forwards but still have some concerns about where those poms are being no longer generated...
