### ISSUE TITLE
Enhancement: Would love a feature to fail the build if any formatting occurs

### ISSUE THREAD

**Issue by fzakaria** [revelc/formatter-maven-plugin#158]
I want to include `formatter-maven-plugin` to my maven project but I think it would be great for my build system to catch any commits that don't adhere to the formatting
(i.e. someone can change the code and commit without running the formatter)

A flag to add "failBuildIfFormat" would be great to add to the continuous build system to catch these!

**Comment by hazendaz** [comment]
That logic is in release 2.0.0.  There is a goal to check formatting that will fail it.

Get Outlook for Android<https://aka.ms/ghei36>



On Sat, Jan 14, 2017 at 12:40 PM -0500, "Farid Zakaria" <notifications@github.com<mailto:notifications@github.com>> wrote:


I want to include formatter-maven-plugin to my maven project but I think it would be great for my build system to catch any commits that don't adhere to the formatting
(i.e. someone can change the code and commit without running the formatter)

A flag to add "failBuildIfFormat" would be great to add to the continuous build system to catch these!

**Comment by fzakaria** [comment]
missed that....
Okay, maybe change this to add documentation.
👍 

I'm not clear what the aggregator does.

**Comment by hazendaz** [comment]
Yes docs probably need some updating.  Go ahead and try what we have and if you can raise a PR to help clarify docs that would be great.  Not sure many have used the new features yet.  If you run into any issues let me know.

Get Outlook for Android<https://aka.ms/ghei36>



On Sat, Jan 14, 2017 at 1:27 PM -0500, "Farid Zakaria" <notifications@github.com<mailto:notifications@github.com>> wrote:


missed that....
Okay, maybe change this to add documentation.
👍

I'm not clear what the aggregator does.

**Comment by hazendaz** [comment]
Updated docs for site per #187 

Seems like our site is not properly updating but I'm trying a few things and will open a new ticket if I cannot get that working.  Otherwise closing this issue as documentation now notes validation information.
