### ISSUE TITLE
Clearer error messages needed on validation error

### ISSUE THREAD

**Issue by huitseeker** [revelc/formatter-maven-plugin#172]
In its current state, when the `validate` goal is activated in an execution, formatting errors create the following message:

```
[ERROR] Failed to execute goal net.revelc.code.formatter:formatter-maven-plugin:2.0.0:validate (default) on project nd4j-api: File '/home/raver119/develop/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/factory/Nd4j.java' format doesn't match! -> [Help 1]
```

Without more insights, it's hard to figure out what the formatter does not like — it would be useful to have a more specific error message, with a line number pointing to the first error.

**Comment by hazendaz** [comment]
I do agree but at the root it's just saying formatting was not performed by developer and then committed to repo.  So solution is for developer to run build and commit changes.

Will keep this open though as it has merit.

Get Outlook for Android<https://aka.ms/ghei36>


________________________________

**Comment by hazendaz** [comment]
@huitseeker I have updated the warning to be more clear.  I'm pushing a fix shortly.

Here is the new message you will see...

```java
 throw new MojoFailureException("File '" + file + "' has not been previously formatted.  Please format file and commit before running validation!");
```

**Comment by huitseeker** [comment]
@hazendaz thanks!
