### ISSUE TITLE
Fix broken update site for m2e

### ISSUE THREAD

**Issue by endrejeges** [revelc/formatter-maven-plugin#177]
The M2e configurator update site (http://revelc.github.io/formatter-maven-plugin/p2/2.0.0) in the README.md seems to be broken.

When trying to add the site to Available Software Sites in Eclipse Mars 3 it says: "No software site found at http://revelc.github.io/formatter-maven-plugin/p2/2.0.0. Do you wish to edit the location?"

When I tried to go to the site location in a browser, then it redirected (HTTP 301 Moved Permanently) me to http://code.revelc.net/formatter-maven-plugin/p2/2.0.0, and then returned an HTTP 404 Not Found.

**Comment by hazendaz** [comment]
I'm not convienced now that we need m2e plugin solution at all.  Maven has a very simple solution by adding the requirements for m2e directly into the plugin so eclipse knows what to do.  The question then becomes what do we want it to actually do there (run on import, run on incremental and full builds, ?)

**Comment by ctubbsii** [comment]
@hazendaz Can you link to some of the documentation for the solution you're referring to? I'd like to learn more about that. If it's possible to avoid the separate plugin, that's very appealing to me. I never use a plugin in Eclipse anyway. I usually set m2e to ignore execution of the Maven plugin during the build, and only run it on the command-line.

**Comment by hazendaz** [comment]
Sorry I should have posted what I found and have determined works for others that I was able to configure in a super pom.  That ignore we all do is wrong, that just tells eclipse to do nothing.  That provides ability to set the right values for what is needed.  For example, some people using googles error prone which I recently started doing figured out how to make it inherit externally what the maven compiler was doing and thus it works whereas ignore would cause import to not create .classpath.  So given that I tried a number of plugins such as wsimport and build helper both of which now without any m2e work perfectly find in eclipse.  Also, you just stub that under src/main/resources and the plugin then will allow eclipse to know what it needs to do.  I don't have a sample with me right now but once I determine it can work on this library I would go as far as dropping any need for m2e directly as it is unnecessary overhead we don't have working yet.

**Comment by hazendaz** [comment]
@ctubbsii [here](http://www.eclipse.org/m2e/documentation/m2e-making-maven-plugins-compat.html).

So I think we really don't want our plugin to do anything for the format goal.  The verify goal we might want but not certain. Beyond that it is pretty clear that we shouldn't really be mixing m2e with our maven plugin which has been a painpoint with releasing.  I still think we need to split but need to look more at those new formatters too.  I haven't had a lot of time for this recently.

**Comment by hazendaz** [comment]
@endrejeges can you try manually downloading the site and loading to eclipse?  That way is working currently.  You can find the site here on maven central [here](http://search.maven.org/remotecontent?filepath=net/revelc/code/formatter/net.revelc.code.formatter.site/2.0.1/net.revelc.code.formatter.site-2.0.1.zip)

**Comment by ctubbsii** [comment]
This issue can be closed now, since this repo no longer contains the m2e-configurator code. That has moved to https://github.com/revelc/formatter-m2e-configurator and should be addressed there in a new issue.
