### ISSUE TITLE
javadoc formatter doesn't seem to work

### ISSUE THREAD

**Issue by hazendaz** [revelc/formatter-maven-plugin#192]
In prior versions of this plugin, javadocs would format.  I'm noticing that it looks like javadocs are no longer formatting.  If I use eclipse to run format it works fine.  I have confirmed both my eclipse settings and format settings match.

**Comment by ctubbsii** [comment]
Oh no. This just hit me, too.

**Comment by mateusz-matela** [comment]
Hi, I'm the current owner of the Eclipse formatter.

I didn't test this, but I'm fairly certain it will be enough to change the kind argument passed to the formatter from `CodeFormatter.K_COMPILATION_UNIT`
to `CodeFormatter.K_COMPILATION_UNIT | CodeFormatter.F_INCLUDE_COMMENTS`.

According to javadoc, it was always supposed to work this way, but apparently the formatter used to ignore this missing flag until it was "fixed" in Eclipse 3.5.

Hope this helps!

**Comment by hazendaz** [comment]
@mateusz-matela Thank you so much!  That was the issue.  I'm applying the fix in #210 now.

**Comment by ctubbsii** [comment]
Awesome! Now, we just need a release pushed to Maven Central :wink:
I'm willing to do that, if somebody has some release instructions. I recall a release being somewhat painful last time. I'm used to the `maven-release-plugin`, but I don't think this project currently works with that. At the very least, I can test a release candidate in the Sonatype staging repo, if that would help.

**Comment by hazendaz** [comment]
I'm unable to run a local release at the moment as the new formatters tests produce different results on my machine. I assume line ending related.  I would also like to do a few extra things before that is ready.
