### ISSUE TITLE
Support WSDL/XSD with xml formatters

### ISSUE THREAD

**Issue by hazendaz** [revelc/formatter-maven-plugin#212]

**Comment by jam01** [comment]
Maybe this works now?

**Comment by jam01** [comment]
Ran a WSDL through the xml formatter, everything looks good. Was there any specific handling you were looking for?

**Comment by hazendaz** [comment]
This didn't work with jsoup very well.  I suspect now it will work well but have not tested it.  XML is XML so I suspect all edge cases should be good at this point :)
