### ISSUE TITLE
New css, html, and xml are not initialized and don't work

### ISSUE THREAD

**Issue by hazendaz** [revelc/formatter-maven-plugin#220]
Initializing them does cause them to work but order of events is odd.  If no file present for properties which is most likely due to it's non maven read state currently, it has already formatted at that point and just applies whatever it did.  The properties are continually read in again and again.  This would be extremely slow on large code bases as there is zero reason to keep doing that.  So it excessively is throwing errors.

**Comment by hazendaz** [comment]
Due to current state of this, we should not push a release until this is fixed or we should entirely disable the new features so we can fix old issues.  I'll try to take some time to fix this over next week but if I don't find the time may just patch to disable for now and move on.  The default settings it uses are pretty bad.

**Comment by ctubbsii** [comment]
I'm starting to wonder if these extra formatters should be in their own goal/mojo, rather than polluting the one for java (which is the only one I care about, personally). It might make the configuration and out-of-box behavior a bit more sane for each goal, at the cost of some slight extra complexity in configuring executions of all the plugin goals you need.

**Comment by hazendaz** [comment]
Although I never got javascript formatting even going I do see value in all these if they reasonably format in one go.  I haven't had any time to come back and look at these but hoping I get some time in the next few weeks.

**Comment by ctubbsii** [comment]
Maybe a `format-all` goal would be good for formatting everything that the plugin can handle, but if a `format-java` option were available to only do java, I would prefer that, rather than execute `format` with a bunch of configuration to skip the formatting features I don't need/want.

**Comment by hazendaz** [comment]
Closing as fixed via #228
