### ISSUE TITLE
Resolve confusing license discrepancy on some modules

### ISSUE THREAD

**Issue by ctubbsii** [revelc/formatter-maven-plugin#244]
The project LICENSE is Apache License, Version 2, and this project has always been Apache licensed. However, some commits made it in from @velo for the m2e-configurator stuff, that appear to be under the Eclipse Public License, 1.0.

This issue is an attempt to request permission from Marvin, as the apparent author of those commits, for the project to release and distribute those portions under the terms of the Apache License, so there's no confusion in future.

**Comment by velo** [comment]
Hey @ctubbsii what files are you talking about?!

I manually checked some and they are ASL2

**Comment by ctubbsii** [comment]
Hi @velo ; I'm referring to:
* m2e-configurator/net.revelc.code.formatter.feature/license.html
* m2e-configurator/net.revelc.code.formatter.feature/feature.properties
* m2e-configurator/catalog.xml

I'm actually not even sure what that catalog.xml file is for. I can't figure out how it's being used at all.

**Comment by velo** [comment]
Ow, absolutely, got for it.  All the code is ASL, no reason for this files to be anything else.

`catalog.xml` may not be in use at the moment.
