### ISSUE TITLE
Remove maven wrapper stuff

### ISSUE THREAD

**Issue by ctubbsii** [revelc/formatter-maven-plugin#250]
I'm not convinced the maven wrapper stuff is helpful for anything. I think it can be removed, since it just seems to add clutter.

Please correct me if I'm wrong.

**Comment by hazendaz** [comment]
It's used on Travis ci

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ctubbsii** [comment]
Right, but it doesn't have to be used there. Travis has maven, and doesn't need a wrapper for it.

**Comment by hazendaz** [comment]
For 3.5.0 it does.  They run 3.2.5 still.  It's intended to use newer versions.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ctubbsii** [comment]
I see. The build works fine on what they have, especially after the recent simplifications, so I think it's okay to leave it out. I think it's more important to keep the repo clear of clutter, for potential contributors and users, than to build with latest Maven on optional CI service.

**Comment by hazendaz** [comment]
Other purpose is that it means you don't actually need maven installed to build our project.  The wrapper serves the purpose of retrieving maven if missing.  This was built as a result of gradle doing something similar with their own wrapper.

**Comment by hazendaz** [comment]
btw - I got a chance to look over everything you have been doing.  Awesome Job!

**Comment by ctubbsii** [comment]
I think it's probably okay to assume that Maven is installed, as a prerequisite. That's pretty normal. Anybody building, or using this project will be doing so specifically because they are already working with Maven projects.

And, thanks for the positive feedback. I'm a bit uncertain at some points where there's multiple paths forward... because I don't want to be seen as "taking over" or doing anything unilaterally. If I overstep and do anything you (or any other contributor) disagrees with, I'm happy to step back (revert if necessary) and discuss to develop consensus before moving forward again. I'm still going to do PRs whenever possible, just to give more opportunities for feedback/review before moving forward, but I might merge them before anybody reviews, if I'm confident in them and I don't hear anything in a reasonable amount of time. I know not everybody can review immediately, but I'm okay with rolling back, too, if the review comes after the merge.

**Comment by hazendaz** [comment]
All good here.  Peronsally I like the workflow of always creating PR even if self merged.  I thinks its just good practice as it puts it out there plus confirning the CI builds work.

I think now we are ready to move to oxygen officially ;)  I'm going to send a few PRs once I get everything setup.  I'm forking all the new repos plus forked your impsort.  Thanks.
