### ISSUE TITLE
Update for Eclipse Oxygen

### ISSUE THREAD

**Issue by ctubbsii** [revelc/formatter-maven-plugin#255]
I'm not even sure if the formatter changed at all between Neon and Oxygen... but either way, we should update to the latest jdt-core dependency and formatter, so it's available to users.

**Comment by hazendaz** [comment]
I ran a test on good sized project.  At least for java code, no changes.  Not sture on javascript as I still have yet to use that formatter.

**Comment by ctubbsii** [comment]
If there's no significant changes, a minor version bump would probably be best. Probably to 2.7.0.

I wouldn't worry about the javascript one that much. I doubt it's getting more active maintenance than the java one.

**Comment by ctubbsii** [comment]
@hazendaz Please, don't forget to push the tag corresponding to the release :smile:

**Comment by hazendaz** [comment]
What are the tags not auto pushing?  That usually happens with release plugin, are we missing a setup?  I'll push it now.  Thanks.

**Comment by hazendaz** [comment]
I'm guessing one of those settings changes on release.  I checked another repo of mine to be sure.  OK all pushed now.

**Comment by ctubbsii** [comment]
It's bad to auto-push tags on release, because:

1. It can't be reviewed first, and it's bad form to delete git tags after pushing to a shared space, because of the way git tags are treated as "universal" and names should not be reused; this is particular important in communities which vote on release candidates before releasing, and
2. The tag that is created is not a GPG-signed tag, which many prefer, for releases, as it gives extra confidence in a particular tag representing an official release; not pushing allows for the option of creating a GPG-signed tag in its place, and pushing that instead.

For these reasons, the `pushChanges` and `localCheckout` flags are commonly set to `false` and `true`, respectively in the `maven-release-plugin`. This was the case in the takari parent POM we were previously using, and it continues to be the case after I removed that parent POM. It's the case for all of the `revelc` projects, as well as many Apache projects. I've even heard from some upstream Apache Maven developers about how they wished this were the default for git for some of these reasons, but could not change it without breaking backwards compatibility, especially for projects still using SVN, where tags don't work the same.

**Comment by ctubbsii** [comment]
Oh, a third reason is that it allows for testing the release process itself.
