### ISSUE TITLE
"Class or interface declaration" (org.eclipse.jdt.core.formatter.brace_position_for_type_declaration) does not work with "next line"

### ISSUE THREAD

**Issue by smatei** [revelc/formatter-maven-plugin#266]
I have set the "Class or interface declaration" formatting preference to "next line" in eclipse, and exported it to a multi-module "build-tools" src\main\resources\eclipse\formatter.xml. When compiling the project with maven I get the following output, that tells me that my file Test.java is formatted (I am on Windows 10 64 bits, and use JDK build 1.8.0_151-b12 on 64 bits, with maven 3.5.0).

> 		
		$ mvn clean compile
		[INFO] Scanning for projects...
		[INFO] ------------------------------------------------------------------------
		[INFO] Reactor Build Order:
		[INFO]
		[INFO] all
		[INFO] utils
		[INFO]
		[INFO] ------------------------------------------------------------------------
		[INFO] Building all 0.0.1-SNAPSHOT
		[INFO] ------------------------------------------------------------------------
		[INFO]
		[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ all ---
		[INFO]
		[INFO] --- formatter-maven-plugin:2.7.1:format (default) @ all ---
		[INFO] Using 'UTF-8' encoding to format source files.
		[INFO] Number of files to be formatted: 0
		[INFO]
		[INFO] ------------------------------------------------------------------------
		[INFO] Building utils 0.0.1-SNAPSHOT
		[INFO] ------------------------------------------------------------------------
		[INFO]
		[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ utils ---
		[INFO] Deleting D:\_git\parent\utils\target
		[INFO]
		[INFO] --- formatter-maven-plugin:2.7.1:format (default) @ utils ---
		[INFO] Using 'UTF-8' encoding to format source files.
		[INFO] Number of files to be formatted: 1
		[INFO] Successfully formatted:          1 file(s)
		[INFO] Fail to format:                  0 file(s)
		[INFO] Skipped:                         0 file(s)
		[INFO] Read only skipped:               0 file(s)
		[INFO] Approximate time taken:          0s
		[INFO]
		[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ utils ---
		[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
		[INFO] skip non existing resourceDirectory D:\_git\parent\utils\src\main\resources
		[INFO]
		[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ utils ---
		[INFO] Changes detected - recompiling the module!
		[WARNING] File encoding has not been set, using platform encoding Cp1252, i.e. build is platform dependent!
		[INFO] Compiling 1 source file to D:\_git\parent\utils\target\classes
		[INFO] ------------------------------------------------------------------------
		[INFO] Reactor Summary:
		[INFO]
		[INFO] all ................................................ SUCCESS [  0.316 s]
		[INFO] utils .............................................. SUCCESS [  1.307 s]
		[INFO] ------------------------------------------------------------------------
		[INFO] BUILD SUCCESS
		[INFO] ------------------------------------------------------------------------
		[INFO] Total time: 1.708 s
		[INFO] Finished at: 2018-01-16T10:00:39+02:00
		[INFO] Final Memory: 29M/482M
		[INFO] ------------------------------------------------------------------------

The file initially looks like this

> 		

		public class Test {
			public static void main(String[] args) {

			
			
			
				System.out.println("bla bla bla");}

			@Override
			public String toString() {

			
			
			
				return super.toString();}
		}

Then, after formatting with the plugin looks like this

> 		

		public class Test {
			public static void main(String[] args) {

				System.out.println("bla bla bla");
			}

			@Override
			public String toString() {

				return super.toString();
			}
		}

If formatted with eclipse looks like this

> 		

		public class Test
		{
		  public static void main(String[] args)
		  {

			System.out.println("bla bla bla");
		  }

		  @Override
		  public String toString()
		  {

			return super.toString();
		  }
		}

I assume that setting

> 		  
			<setting id="org.eclipse.jdt.core.formatter.brace_position_for_type_declaration" value="next_line"/>

from the build-tools\src\main\resources\eclipse\formatter.xml does not work well. I have attached the example, that is a simple multi module project.

[parent.zip](https://github.com/revelc/formatter-maven-plugin/files/1634114/parent.zip)

This is the version of the plugin that I use

> 		  
			<plugins>
			  <plugin>
				<groupId>net.revelc.code.formatter</groupId>
				<artifactId>formatter-maven-plugin</artifactId>
				<version>2.7.1</version>
				<executions>
				  <execution>
					<goals>
					  <goal>format</goal>
					</goals>
				  </execution>
				</executions>
				<configuration>
				  <configFile>eclipse/formatter.xml</configFile>
				  <encoding>UTF-8</encoding>
				  <lineEnding>AUTO</lineEnding>
				</configuration>
				<dependencies>
				  <dependency>
					  <groupId>com.github.hazendaz</groupId>
					  <artifactId>build-tools</artifactId>
					  <version>1.1.6</version>
				  </dependency>
				</dependencies>
			  </plugin>
			</plugins>

**Comment by hazendaz** [comment]
Try dropping back to version 2.7.0.  There are known issues in 2.7.1 waiting on eclipse fixes.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by smatei** [comment]
The problem is not with the version. I went back to version 2.5.0 and no luck. Then I executed maven in verbose mode "mvn clean compile -X" and saw the problem "eclipse/formatter.xml not found"

> 		
 		[DEBUG] The resource 'eclipse/formatter.xml' was not found with resourceLoader org.codehaus.plexus.resource.loader.FileResourceLoader.
		[DEBUG] URLResourceLoader: No valid URL 'eclipse/formatter.xml'
		[DEBUG] The resource 'eclipse/formatter.xml' was not found with resourceLoader org.codehaus.plexus.resource.loader.URLResourceLoader.
		[DEBUG] The resource 'eclipse/formatter.xml' was not found with resourceLoader org.codehaus.plexus.resource.loader.ThreadContextClasspath                                                                                                                                ResourceLoader.
		[DEBUG] The resource 'eclipse/formatter.xml' was not found with resourceLoader org.codehaus.plexus.resource.loader.JarResourceLoader.
		[DEBUG] Config file [eclipse/formatter.xml] cannot be found
		org.codehaus.plexus.resource.loader.ResourceNotFoundException: Could not find resource 'eclipse/formatter.xml'.
				at org.codehaus.plexus.resource.DefaultResourceManager.getResource(DefaultResourceManager.java:171)
				at org.codehaus.plexus.resource.DefaultResourceManager.getResourceAsInputStream(DefaultResourceManager.java:67)
				at net.revelc.code.formatter.FormatterMojo.getOptionsFromConfigFile(FormatterMojo.java:705)
				at net.revelc.code.formatter.FormatterMojo.getFormattingOptions(FormatterMojo.java:690)
				at net.revelc.code.formatter.FormatterMojo.createCodeFormatter(FormatterMojo.java:642)
				at net.revelc.code.formatter.FormatterMojo.execute(FormatterMojo.java:335)
				at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
				at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
				at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
				at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
				at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
				at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
				at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
				at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
				at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
				at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
				at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
				at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
				at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
				at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
				at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
				at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
				at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
				at java.lang.reflect.Method.invoke(Method.java:498)
				at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
				at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
				at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)

If I set the configuration file like this

>         
          <configFile>../build-tools/src/main/resources/eclipse/formatter.xml</configFile>
          <encoding>UTF-8</encoding>
          <lineEnding>AUTO</lineEnding>

it works. I got the example from [your documentation](http://code.revelc.net/formatter-maven-plugin/examples.html#Multimodule_Configuration) - <configFile>eclipse/formatter.xml</configFile>.  This does not seem to work, or I am missing something.

**Comment by ctubbsii** [comment]
Are you sure that file exists in the build-tools dependency? (e.g. `jar tf build-tools.jar | grep eclipse/formatter.xml`)

**Comment by smatei** [comment]
The file exists, this is the output of your search command

> 		
		stefan@StefanPC MINGW64 /d/_git/parent/build-tools/target
		$ jar tf build-tools-0.0.1-SNAPSHOT.jar | grep eclipse/formatter.xml
		eclipse/formatter.xml

I still get the error in verbose mode (mvn clean compile -pl utils -X) when compiling my project

> 		
		[DEBUG] Config file [eclipse/formatter.xml] cannot be found
org.codehaus.plexus.resource.loader.ResourceNotFoundException: Could not find resource 'eclipse/formatter.xml'.

I will stick to the relative path "../build-tools/src/main/resources/eclipse/formatter.xml". This works. You can play with the parent.zip attached to my first post. Either I am missing something (in my pom.xml), or the class path reference does not work.

**Comment by hazendaz** [comment]
I haven't look at your zip but sounds like you created a jar with the contents in same project you are attempting to use the jar.  If I'm correct on that, it's not going to work from that jar unless you physically make the project dependent on that jar so it gets built first by the reactor, is installed, and then can be used.  Generally a jar usage is entirely separate project.  Can you confirm if that is the case?  If so just try adding the jar as a dependency on provided scope or relative path is correct in that case.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ctubbsii** [comment]
I took a look at the zip file. In it, you are using:

```xml
				  <groupId>com.github.hazendaz</groupId>
				  <artifactId>build-tools</artifactId>
				  <version>1.1.6</version>
```

The contents of that jar are:

```
META-INF/MANIFEST.MF                                                                                
META-INF/                                                                                           
META-INF/maven/                                                                                     
META-INF/maven/com.github.hazendaz/                                                                 
META-INF/maven/com.github.hazendaz/build-tools/                                                     
checkstyle.xml                                                                                      
xml.properties                                                                                      
css.properties                                                                                      
META-INF/maven/com.github.hazendaz/build-tools/pom.properties                                       
eclipse-formatter-config-2space.xml                                                                 
eclipse-formatter-config-4space.xml                                                                 
eclipse-formatter-config.xml                                                                        
META-INF/maven/com.github.hazendaz/build-tools/pom.xml                                              
eclipse-java-google-style.xml                                                                       
eclipse-js-formatter-config.xml                                                                     
html.properties      
```

There is no `eclipse/formatter.xml`

If you wish to use that jar's formatter, you'll have to specify it correctly (such as `eclipse-formatter-config-4space.xml` instead of `eclipse/formatter.xml`). If you wish to use your own formatter from your own build-tools artifact, you'll need to ensure your own artifact containing your own formatter is specified as the dependency of the formatter-maven-plugin instead of the hazendaz one.

**Comment by smatei** [comment]
Now I get it. The example was confusing. It was defining a build-tools and it was using another build-tools as dependeny. I have a pull request with the fix so that it is not confusing any more.

[https://github.com/revelc/formatter-maven-plugin/pull/267](https://github.com/revelc/formatter-maven-plugin/pull/267)

**Comment by hazendaz** [comment]
See my comment on pull request.  I dont see any clarity by referencing another jar.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
