### ISSUE TITLE
Enhancement request: XML Formatting

### ISSUE THREAD

**Issue by GoogleCodeExporter** [revelc/formatter-maven-plugin#27]
```
Eclipse stores its XML format preferences in a separate config file. 
Export->preferences

This is configured from XML->XML Files->Editor

Could you please update this plugin to support XML formatting using Eclipse's 
XML format config?
```

Original issue reported on code.google.com by `ndeck...@gmail.com` on 27 Mar 2013 at 7:15

**Comment by hazendaz** [comment]
This project solves XML formatting -> https://github.com/velo/maven-formatter-plugin.  I think we bring him into the fold so we get a one size fits all solution if he is willing.  He forked long ago from this project and it currently shows the fork from github so he may be willing to spin these back together.

**Comment by velo** [comment]
FWIW, I only solved JS format....

XML, HTML, ?ML still pending!

**Comment by hazendaz** [comment]
Found a viable solution for xml formatting.

https://github.com/benalexau/xml-formatter

**Comment by hazendaz** [comment]
#196 solved this issue.
