### ISSUE TITLE
Maven Install Does Not Remove Spaces in Block Comments

### ISSUE THREAD

**Issue by yash-tib** [revelc/formatter-maven-plugin#271]
I have set up the maven-formatter-plugin (v2.7.0) to format and validate our repo with the following comments related rules -

```
<setting id="org.eclipse.jdt.core.formatter.comment.clear_blank_lines_in_block_comment" value="true"/>
<setting id="org.eclipse.jdt.core.formatter.comment.clear_blank_lines_in_javadoc_comment" value="true"/>
<setting id="org.eclipse.jdt.core.formatter.comment.format_block_comments" value="true"/>
<setting id="org.eclipse.jdt.core.formatter.comment.format_header" value="false"/>
<setting id="org.eclipse.jdt.core.formatter.comment.format_html" value="true"/>
<setting id="org.eclipse.jdt.core.formatter.comment.format_javadoc_comments" value="true"/>
<setting id="org.eclipse.jdt.core.formatter.comment.format_line_comments" value="true"/>
<setting id="org.eclipse.jdt.core.formatter.comment.format_source_code" value="true"/>
<setting id="org.eclipse.jdt.core.formatter.comment.indent_parameter_description" value="true"/>
<setting id="org.eclipse.jdt.core.formatter.comment.indent_root_tags" value="true"/>
<setting id="org.eclipse.jdt.core.formatter.comment.insert_new_line_before_root_tags" value="insert"/>
<setting id="org.eclipse.jdt.core.formatter.comment.insert_new_line_for_parameter" value="insert"/>
<setting id="org.eclipse.jdt.core.formatter.comment.line_length" value="120"/>
<setting id="org.eclipse.jdt.core.formatter.comment.new_lines_at_block_boundaries" value="true"/>
<setting id="org.eclipse.jdt.core.formatter.comment.new_lines_at_javadoc_boundaries" value="true"/>
<setting id="org.eclipse.jdt.core.formatter.comment.preserve_white_space_between_code_and_line_comments" value="false"/>
<setting id="org.eclipse.jdt.core.formatter.format_line_comment_starting_on_first_column" value="true"/>
<setting id="org.eclipse.jdt.core.formatter.join_lines_in_comments" value="true"/>
<setting id="org.eclipse.jdt.core.formatter.never_indent_block_comments_on_first_column" value="false"/>
<setting id="org.eclipse.jdt.core.formatter.never_indent_line_comments_on_first_column" value="false"/>
```

Upon validate, the build fails if there is a block comment with an empty line containing a single space. eg :-

```
 /*
  * Some Text Here
  *<SPACE>
  * @author ytib
  */
```

However, the maven format goal during ```mvn clean install``` does not format this particular case. All other cases are formatted properly. IntelliJ, on the other hand, is able to properly format this case as well.

Help would be deeply appreciated! :)

**Comment by hazendaz** [comment]
There is a bug in eclipse.  Try source clean up  in eclipse without this plugin.  You will notice it toggles between space and no space.  I'm not sure how we can fix that.  It's part of eclipse source cleanup rather than formatting.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ctubbsii** [comment]
This bug in Eclipse has been a long frustration of mine, and I've not found good workarounds. One good thing is that if you delete the spaces in Javadoc comments, they won't be re-added. However, in block comments (non-Javadoc), they do tend to reappear. I have in the past used multiple inline comments instead of block comments as a workaround, but that's not the best option.

In your example, you used a multi-line (non-Javadoc) comment, but with Javadoc tags. The good news is that if you intended this to be a Javadoc comment block, and you remove the space, it should not be re-added.

**Comment by yash-tib** [comment]
Thanks for your replies.

But essentially what I am trying to convey is that the validate goal is failing the build if a space exists in the comment. But the format goal does not correct this behaviour so that the validate goal can pass. Is this the defined behaviour? Because while the space might have been introduced by eclipse sometime in the past, on my current machine I am running IntelliJ, so if the maven formatter is deleting the space, there is no chance that eclipse could reintroduce it.

It doesn't actually matter to me if the space exists or not. Could you please help me identify the config to align the format and validate goals such that once I run format, the validate should pass?

**Comment by ctubbsii** [comment]
@yash-tib I think you're misunderstanding the responses regarding Eclipse. This plugin uses the Eclipse formatter internally, so if Eclipse would have reintroduced a space, then this plugin does as well, whether or not you yourself are using Eclipse.

That said, there may be something else going on here... I've never seen the validate goal fail if the format goal did not make any changes. How are you running these two goals, specifically (what command line, how is the POM configured, etc.)? Can you provide an example project which reproduces the problem?

**Comment by yash-tib** [comment]
@ctubbsii 

We are using the following config in our maven file -

`
  <properties>
     <maven.formatter.version>2.7.0</maven.formatter.version>
     <maven.xml.formatter.version>3.0.6</maven.xml.formatter.version>
     <eclipse.lifecycle.mapping.version>1.0.0</eclipse.lifecycle.mapping.version>
     <java.coding.standard.version>2017.1</java.coding.standard.version>
     <xml.indent.size>2</xml.indent.size>
  </properties>
   <build>
      <plugins>
         <plugin>
            <groupId>net.revelc.code.formatter</groupId>
            <artifactId>formatter-maven-plugin</artifactId>
            <executions>
               <execution>
                  <goals>
                     <goal>format</goal>
                  </goals>
               </execution>
            </executions>
         </plugin>
         <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-surefire-plugin</artifactId>
            <configuration>
               <forkMode>once</forkMode>
               <argLine>-Xms2048m -Xmx2048m</argLine>
            </configuration>
         </plugin>
         <plugin>
            <groupId>au.com.acegi</groupId>
            <artifactId>xml-format-maven-plugin</artifactId>
            <version>${maven.xml.formatter.version}</version>
            <executions>
               <execution>
                  <id>xml-format</id>
                  <goals>
                     <goal>xml-format</goal>
                  </goals>
                  <configuration>
                     
                     <indentSize>${xml.indent.size}</indentSize>
                  </configuration>
               </execution>
            </executions>
         </plugin>
      </plugins>
      <pluginManagement>
         <plugins>
            
            <plugin>
               <groupId>org.eclipse.m2e</groupId>
               <artifactId>lifecycle-mapping</artifactId>
               <version>1.0.0</version>
               <configuration>
                  <lifecycleMappingMetadata>
                     <pluginExecutions>
                        <pluginExecution>
                           <pluginExecutionFilter>
                              <groupId>net.revelc.code.formatter</groupId>
                              <artifactId>formatter-maven-plugin</artifactId>
                              <versionRange>[2.7.0,)</versionRange>
                              <goals>
                                 <goal>format</goal>
                              </goals>
                           </pluginExecutionFilter>
                           <action>
                              <ignore />
                           </action>
                        </pluginExecution>
                     </pluginExecutions>
                  </lifecycleMappingMetadata>
               </configuration>
            </plugin>
            <plugin>
               <groupId>net.revelc.code.formatter</groupId>
               <artifactId>formatter-maven-plugin</artifactId>
               <version>${maven.formatter.version}</version>
               <configuration>
                  <configFile>eclipse-neon/eclipse-formatter.xml</configFile>
                  <lineEnding>CRLF</lineEnding>
                  <encoding>UTF-8</encoding>
               </configuration>
               <dependencies>
                  <dependency>
                     <groupId>com.paypal.standards</groupId>
                     <artifactId>java-coding-standards</artifactId>
                     <version>${java.coding.standard.version}</version>
                  </dependency>
               </dependencies>
            </plugin>
         </plugins>
      </pluginManagement>
   </build>
   <profiles>
      <profile>
         <id>validate-format</id>
         <build>
            <plugins>
               <plugin>
                  <groupId>net.revelc.code.formatter</groupId>
                  <artifactId>formatter-maven-plugin</artifactId>
                  <executions>
                     <execution>
                        <goals>
                           <goal>validate</goal>
                        </goals>
                     </execution>
                  </executions>
               </plugin>
            </plugins>
         </build>
      </profile>
   </profiles>
`

And we have added the validate goal to our Jenkins CI by adding the following command in the maven build arguments `-Pvalidate-format`. the validate fails intermittently if the space is present in the block comment. It sometimes fails, and sometimes passes in the Jenkins build. The comment related rules in the formatter are entered in the original comment. Please let me know if I should add the other rules as well.

**Comment by wmarkow** [comment]
Could you please post the Maven output, so we could see what is the error message? If you run Maven with **-X** option, it will output more debug information on what is going on.

**Comment by yash-tib** [comment]
@ctubbsii Thanks for the clues, I will keep this in mind. We ended up fixing the issue by removing all the block comments with spaces in our codebase. Since then we have not been able to reproduce the issue. I am hence closing this issue and will reopen it if we face any trouble in the future.

Thanks for all the help! :)
