### ISSUE TITLE
No error message if configured formatter config file is not found

### ISSUE THREAD

**Issue by leblonk** [revelc/formatter-maven-plugin#275]
When the configured formatting file cannot be found, the plugin silently reverts to using the default config. To reproduce, add config:
 
>        <configuration>
>          <configFile>does-not-exist.xml</configFile>
>        </configuration>
Result: formatting happens anyway, but with incorrect (default) formatting rules

Desired result: plugin throws an error and the build fails

Other data, running maven --debug will show a file not found stacktrace for the missing file

**Comment by dmasyukov** [comment]
Hopefully my pull request will be merged to fix this issue

**Comment by ctubbsii** [comment]
Fixed by #284
