### ISSUE TITLE
Add support for @formatter:on and @formatter:off

### ISSUE THREAD

**Issue by santiagozky** [revelc/formatter-maven-plugin#276]
The plugin doesnt seem to support the @formatter:on/off comments, which allow you to preserve the format of certain sections of code.

in the eclipse xml config they look like
<setting id="org.eclipse.jdt.core.formatter.enabling_tag" value="@formatter:on"/>
and 
<setting id="org.eclipse.jdt.core.formatter.disabling_tag" value="@formatter:off"/>

They are particularly (for me )useful when dealing with large enums when the formatter can format them pretty weirdly and hard to read.

**Comment by ctubbsii** [comment]
It does support them. You just need to make sure whatever formatter configuration you are using has them enabled.
```xml
<setting id="org.eclipse.jdt.core.formatter.use_on_off_tags" value="true"/>
```

**Comment by santiagozky** [comment]
hi. you are absolutely right! mi config file is wrong.
Thank you very much and sorry for the noise.

**Comment by ctubbsii** [comment]
@santiagozky Not a problem at all. Glad you got it working. Feel free to file issues (or pull request) to identify bugs and suggest changes whenever you encounter a problem.
