### ISSUE TITLE
Allow JSON formatter to omit space before separator

### ISSUE THREAD

**Issue by EtonDoze** [revelc/formatter-maven-plugin#279]
JSON by default puts a space before and after separator `:` e.g.
```
{
  "first_name" : "John",
  "last_name" : "Doe"
}
```
Instead, we would like to skip that space before `:` and have the final JSON look like
```
{
  "first_name": "John",
  "last_name": "Doe"
}
```
This style is in sync with most popular JSON formatters on web and within IDEs.

**Comment by ctubbsii** [comment]
You don't need to create an issue *AND* a pull request. On GitHub, pull requests *ARE* issues, so creating an extra issue is redundant.

**Comment by EtonDoze** [comment]
Got it. Closing this issue. Lets resume on PR https://github.com/revelc/formatter-maven-plugin/pull/280
