### ISSUE TITLE
use_on_off_tags to true

### ISSUE THREAD

**Issue by GoogleCodeExporter** [revelc/formatter-maven-plugin#28]
```
Hi guys,

Does your useful plugin support  
"org.eclipse.jdt.core.formatter.use_on_off_tags" with true value ? it is about 
@formatter:off - @formatter:on flags..

I'm not able having this working ... may it is my error or ... ?

Expected output: code between @formatter:off and @formatter:on not formatted

Actual output: code between @formatter:off and @formatter:on not formatted

Steps to reproduce:
1. add use_on_off_tags to true in formatter.xml
2. put // @formatter:off and // @formatter:on before a bad formatted portion of 
code
3. mvn java-formatter:format
4. check code in flags is not formatted 

Plugin version: 0.3.1
Maven version:3.0.4
Java version:1.7.0_05, vendor: Oracle
Eclipse version:Juno
OS:Linux Ubuntu

Additional details

here my formatter.xml

```

Original issue reported on code.google.com by `stefano....@gmail.com` on 24 Jun 2013 at 2:28

Attachments:
* [eclipse_formatter.xml](https://storage.googleapis.com/google-code-attachments/maven-java-formatter-plugin/issue-28/comment-0/eclipse_formatter.xml)

**Comment by ctubbsii** [comment]
This actually works, as far as I can tell.

**Comment by hazendaz** [comment]
Based on some searching in google it would appear this tagging had issues early with eclipse but has since been fixed.  I don't use it myself but would assume as of Luna the issues are resolved.  If @ctubbsii has verified it is working as expected I would venture to say it probably is.

**Comment by ctubbsii** [comment]
Cannot reproduce.
