### ISSUE TITLE
Gitlab Ci - Runner under UNIX

### ISSUE THREAD

**Issue by ndaussy** [revelc/formatter-maven-plugin#299]
Hello,

I try to integrate this plugin into my CI. When i run validate phase on my local (Windows) all is ok, validate pass. 
Under Gitlab Ci running with UNIX, validate failed. 

Have you ever have this kind of issue ?

**Comment by hazendaz** [comment]
@ndaussy Sounds like a line ending issue which will just require insurance git is configured correctly. What all files are you validating as we now have numerous pieces?  General git setup would be check in *nix style and checkout as whatever the specific system is set to.  You can additionally control that.

**Comment by ndaussy** [comment]
hi, 

Thanks for you quick feedback, I try to format java file.
I check git to do no change my EOF & set up one file with LF. I continue to have an issue.
btw when i run mvn process-sources in my gitlab runner, change are apply on majority of file

I try with Option <lineEnding>KEEP</lineEnding> but i got same result.

I set up plugin as following :
![SetUpPlugin](https://user-images.githubusercontent.com/6255231/55690783-2c9d8d00-5996-11e9-8401-0e4e974d9b93.PNG)

**Comment by ndaussy** [comment]
One other small question, when i put lineEnding = KEEP, it must not validate under Unix or Windows ? or he will try to validate under system EOF ?

**Comment by ndaussy** [comment]
finally fix issue : 
- Change all file with LF 
- Apply change in all my file to force plugin to run on each of them ( i don't known why sometimes he do not apply change in some file )

Validation pass. Thanks.
