### ISSUE TITLE
Add ability to get the config file from a URL

### ISSUE THREAD

**Issue by GoogleCodeExporter** [revelc/formatter-maven-plugin#30]
```
I would like to get the config xml file from a URL, so that the whole team can 
share the same config.

TIA,
Gabriel
```

Original issue reported on code.google.com by `belingue...@gmail.com` on 1 Oct 2013 at 2:51

**Comment by ctubbsii** [comment]
The best way to do this is to ship the xml config file in a separate maven artifact, and add that as a dependency to the plugin when configuring the plugin. Having maven plugins randomly reach out to a URL is likely to not be a good idea. You never know what you're going to get.

**Comment by hazendaz** [comment]
Agreed.  In fact, I have a side project called build-tools under https://github.com/hazendaz/build-tools that is in fact just this.  It is eclipse 4.4.1 revision of eclipse configuration for this project.

**Comment by mithuns** [comment]
Is this planned in a later version, if it is marked as an enhancement ? I was going to ask for the exact same thing, good thing I searched through the closed issues.
