### ISSUE TITLE
java files in package named "rcs" will be formatted

### ISSUE THREAD

**Issue by Wens-Dany** [revelc/formatter-maven-plugin#300]
When i format my java files, it doesn't work for these files in "rcs" package. Like this,
package com.mytest.rcs;
Number of files to be formatted not contain java files in rcs package. Is it a bug?

**Comment by ctubbsii** [comment]
Can you create an example project on GitHub which demonstrates the problem that I can clone and inspect to investigate this? Thanks.

**Comment by sunwen900815** [comment]
> Can you create an example project on GitHub which demonstrates the problem that I can clone and inspect to investigate this? Thanks.

It adds default excludes file path by this code "ds.addDefaultExcludes();" in "addCollectionFiles" method of "FormatterMojo.java". In method named "addDefaultExcludes" of "AbstractScanner.java", "DEFAULTEXCLUDES" constant contains "**/RCS" and "**/RCS/**". So the package named "rcs" will be excluded by default. Is it the reason of my problem?

**Comment by ctubbsii** [comment]
> So the package named "rcs" will be excluded by default. Is it the reason of my problem?

Possibly. If you create an example project that demonstrates the problem, I can use your example project to try to verify, and identify a solution.

**Comment by ctubbsii** [comment]
Closing this as there is no response in 6 months.
