### ISSUE TITLE
Question: where are the various properties formats/values documented ? 

### ISSUE THREAD

**Issue by maxandersen** [revelc/formatter-maven-plugin#308]
i.e. configXmlFile says it points to a properties file to control the format. 

Where are the documentation for what you can put in that properties file ?

**Comment by jam01** [comment]
They are not formally documented but you can find the default values here...

https://github.com/revelc/xml-formatter/blob/xml-formatter-0.1.1/src/main/java/net/revelc/code/formatter/xml/lib/FormattingPreferences.java
https://github.com/revelc/formatter-maven-plugin/blob/formatter-maven-plugin-2.10.0/src/main/resources/formatter-maven-plugin/eclipse/xml.properties

The next release of the plugin will hopefully include a new property
`wellFormedValidation` whose allowed values are WARN, FAIL, IGNORE

**Comment by ctubbsii** [comment]
Closed as answered, but feel free to reply here, or reopen if you have more to ask about this.
