### ISSUE TITLE
Add parameter to analyse and format ONLY a (list of) file(s)

### ISSUE THREAD

**Issue by mtinel** [revelc/formatter-maven-plugin#310]
In order to automatize the format before each commit, it will be convenient to format only the files to be committed. It will be appreciate to allow analyse and format only a list of files, instead of analys the whole project.
example usage:
`mvn formatter:format -Dformatter.format.files="file1,file2"`

This will improve the process time by skipping the project analyses.
The plugin do not have this functionality or is not (well) documented.

**Comment by ctubbsii** [comment]
I'm pretty sure this is already satisfied with the documented "[includes](https://code.revelc.net/formatter-maven-plugin/format-mojo.html#includes)" option. Please reopen if it doesn't work for you.
