### ISSUE TITLE
Analyse and format ONLY files provided by `formatter.includes` parameter (issue  #310 )

### ISSUE THREAD

**Issue by mtinel** [revelc/formatter-maven-plugin#311]
When i used like this :
mvn formatter:format -Dformatter.includes="module1/src/main/java/package/file.java"
or like this
mvn formatter:format -Dformatter.includes="module1/src/main/java/package/file.java,module1/src/main/java/package/file2.java"
each attempt will format file2.java

tested with versions 2.8.1 and 2.11.0

**Comment by mtinel** [comment]
I have a `<includes>**/src/main/java/**/*.java</includes>` configuration section in my pom.
this should be overrided by the command line parameter `formatter.includes`

**Comment by mtinel** [comment]
Ok, find the (simple) solution:
I set a property
 `<formatter.includes>**/src/main/java/**/*.java</formatter.includes>`
 and set
`<includes>${formatter.includes}</includes>`

**Comment by ctubbsii** [comment]
> I have a `<includes>**/src/main/java/**/*.java</includes>` configuration section in my pom.
> this should be overrided by the command line parameter `formatter.includes`

This has bitten me before, too. This isn't how Maven works. The explicit configuration in the pom takes precedence. I know... it's unintuitive, but your workaround is the general solution to this problem.
