### ISSUE TITLE
Is it possible to specify multiple config xml?

### ISSUE THREAD

**Issue by thescouser89** [revelc/formatter-maven-plugin#318]
Hi,

I was wondering if it would be possible to specify multiple config xml. For example, one to format the code and another one for cleanups (like removing unused import statements).

**Comment by ctubbsii** [comment]
Hi @thescouser89 ; the code formatting that this plugin implements is the Eclipse "Code Style" formatting. It does not implement the Eclipse "Clean Up", "Save Actions", or "Organize Imports" features (at least, not at this time). I don't think those features have nice, easy to use APIs internally, that this plugin could build off of.

You can configure Maven to execute the plugin multiple times, with different configurations, though: https://stackoverflow.com/questions/16540808/can-i-configure-multiple-plugin-executions-in-pluginmanagement-and-choose-from

If you are just looking to organize imports, this other project can do some of that: https://github.com/revelc/impsort-maven-plugin

**Comment by thescouser89** [comment]
Thanks for the quick reply! Much appreciated! :)
