### ISSUE TITLE
Enhanchement : Add a cleanup goal to launch Clean Up with a specific EclipseCleanUpRules in addition of format

### ISSUE THREAD

**Issue by GoogleCodeExporter** [revelc/formatter-maven-plugin#32]
```
Enhanchement : Add a cleanup goal to launch Clean Up with a specific 
EclipseCleanUpRules in addition of format

Tell me if it is not clear.
```

Original issue reported on code.google.com by `alexandr...@gmail.com` on 1 Jan 2014 at 12:56

**Comment by ctubbsii** [comment]
Would this address some of the trailing whitespace problems described in #23 ?

**Comment by hazendaz** [comment]
Yes cleanup action would fix trailing space.  Same applies on eclipse mars

--- Original Message ---

**Comment by chonton-elementum** [comment]
I'm interested in this as well.  Any clues where to start in eclipse code?

**Comment by ctubbsii** [comment]
Not too familiar with the Eclipse codebase, but it seems kinda scattered. Might be best to check in with the Eclipse community to see where the best place to start would be. Hopefully, the code for cleanup is modular enough to be reused here, but it might be a long shot.

**Comment by ambition-consulting** [comment]
Clean Ups have not been externalised like the formatter. Best you could do, is execute Eclipse in Headless mode, e.g. using TEA.

**Comment by delanym** [comment]
Damn this would be so handy

**Comment by ctubbsii** [comment]
FWIW, the whitespace removal is no longer necessary from this, since that feature was added natively without the use of Clean Up actions.

**Comment by hazendaz** [comment]
Closing this as original need was addressed and if intent was a full cleanup, I think that is far beyond scope of the formatter plugin as it is not formatting at all.
