### ISSUE TITLE
Mistake by me on master / will be fixing shortly back to where it was....

### ISSUE THREAD

**Issue by hazendaz** [revelc/formatter-maven-plugin#324]

**Comment by hazendaz** [comment]
Fixed.  Sorry about that.  Quickly realized I pushed to wrong location WIP.

**Comment by hazendaz** [comment]
To clarify, why this happened.  I do everything in powershell normall and releases through git bash in windows.  Becuase project requires jdk 11, I use a quick switch via bash to use 14 in my case.  And thus I was sitting in bash and had also subsequently just released the jsdt-core module.  So I mistakenly thought I was sitting on jsdt-core and running pushes for the release since that is disabled on release from automatically happening.  I caught this immediately when I pushed to my repo and dozens of tags shows up I didn't have.  Then I realized my error.  I think the push up here was for maybe 10 minutes so there is a force push but it is back where it was to start with.

Here is some output from my screen showing this.  I did remove the branch rule and added it back quickly.

```
PS..\GitHub\formatter-maven-plugin> git fetch --all -p
Fetching origin
Fetching revelc
From https://github.com/revelc/formatter-maven-plugin
 - [deleted]         (none)     -> revelc/upgrade-xml
remote: Enumerating objects: 40, done.
remote: Counting objects: 100% (40/40), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 40 (delta 10), reused 34 (delta 6), pack-reused 0
Unpacking objects: 100% (40/40), 9.41 KiB | 34.00 KiB/s, done.
   50ce7a3..**bd50f7c**  master     -> revelc/master
Fetching upstream
From https://github.com/revelc/formatter-maven-plugin
 - [deleted]         (none)     -> upstream/upgrade-xml
   50ce7a3..bd50f7c  master     -> upstream/master
PS..\GitHub\formatter-maven-plugin> **git pull --rebase upstream master**
From https://github.com/revelc/formatter-maven-plugin
 * branch            master     -> FETCH_HEAD
First, rewinding head to replay your work on top of it...
Applying: [pom] Add maven wrapper to 0.5.3
Applying: [mvn] Bump maven to 3.6.3 / maven wrapper to 0.5.6
Applying: [ci] Format the maven wrapper file
Applying: [jvm] Add support for scala / groovy
Applying: [pom] Add some comments - review
```

**Comment by hazendaz** [comment]
Thus force push was back to the bd50f7c commit last on head before I mistakenly pushed.  And while this may not have normally been an issue, I have items that I know @ctubbsii doesn't want on the repo such as maven wrapper and a few other older questions / concerns that were for my own eyes.  Sorry for all the noise.

**Comment by ctubbsii** [comment]
No worries @hazendaz , but thanks for documenting the error and remedy, for transparency sake and to aid anybody who may have cloned or pulled in the brief window. :smiley_cat:
