### ISSUE TITLE
Alphabetize JSON

### ISSUE THREAD

**Issue by StefanoDeVuono** [revelc/formatter-maven-plugin#330]
The JSON formatter uses Jackson which has the ability to alphabetize JSON. I propose added this option to the formatter

**Comment by ctubbsii** [comment]
Sounds like a good idea. Are you willing to submit a pull request?

**Comment by StefanoDeVuono** [comment]
Sure!

**Comment by hazendaz** [comment]
@StefanoDeVuono While you are at it, I noticed that the JSON formatter currently doesn't end in a new line which is more git friendly.  It currently ends at the ending bracket.  Could you potentially see what it takes to keep that extra blank line at the end.  That would ensure it behaves like the java formatter does ;)

**Comment by hazendaz** [comment]
Fixed via #405
