### ISSUE TITLE
Eclipse max line length (LineSplit) not being honored

### ISSUE THREAD

**Issue by jcamerin** [revelc/formatter-maven-plugin#331]
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<profiles version="13">
<profile kind="CodeFormatterProfile" name="MessageGears" version="13">
<setting id="org.eclipse.jdt.core.formatter.join_wrapped_lines" value="true"/>
<setting id="org.eclipse.jdt.core.formatter.lineSplit" value="120"/>
</profile>
</profiles>
```

The following line (133 chars with indentation) in one of my java source files, which should be wrapped into 2 lines does not. If I manually wrap this to two lines, I get an error when running formatter:validate and if I run formatter:format it unwraps the line.

private final HateoasPageableHandlerMethodArgumentResolver pageableResolver = new HateoasPageableHandlerMethodArgumentResolver();

Running formatter 2.11 on Java 8 with Maven 3.5
This behavior occurs both on my local machine as well as on Jenkins

**Comment by ctubbsii** [comment]
This seems related to #289, but for assignment statements, rather than enums.

Eclipse sometimes doesn't honor wrapping options when there is a conflicting configuration. I'm pretty sure the default is to not wrap assignment statements.

In this case, it is probably "alignment_for_assignment" or "align_assignment_statements_on_columns". I recommend importing your configuration into Eclipse, adjusting the wrapping settings and then re-exporting for use with the plugin.

If you still can't find the problem, please provide a minimal example Maven project to demonstrate the issue (complete with your formatter configuration file), and I can try to reproduce or find the correct configuration to change.

**Comment by jcamerin** [comment]
Thank you for the response.

In my Eclipse formatter, I have
<setting id="org.eclipse.jdt.core.formatter.alignment_for_assignment"
value="0"/>
but I do NOT have align_assignment_statements_on_columns

Do you think this is the issue? And what would be the correct setting to
correct the behavior?

**Comment by ctubbsii** [comment]
> Do you think this is the issue? And what would be the correct setting to
correct the behavior?

@jcamerin Please see my previous response, where I suggested courses of action for you to try.

**Comment by jcamerin** [comment]
Thank you for the guidance so far.  I have been able to fix a few formatter
rules that I was unaware were broken. I do have one that I am struggling to
determine where to configure it in Eclipse.  Below is another formatting
issue (consistent with the plugin and inside Eclipse). The Eclipse
formatter is joining the two lines with the two annotations on the method
parameter, making the line longer than 120 characters. As mentioned, I am
struggling to figure out the configuration rule that would wrap this long
line.  Any guidance/hints on what the rule might be would be appreciated.
Thank you
John

     public ResponseEntity<?> getDatabaseConnection(
-            @Description("Id of the Database Connection that will be
returned")
-            @PathVariable("externalDatasourceId") final Integer
externalDatasourceId) {
+            @Description("Id of the Database Connection that will be
returned") @PathVariable("externalDatasourceId") final Integer
externalDatasourceId) {
         LOGGER.trace("getDatabaseConnection");

**Comment by ctubbsii** [comment]
@jcamerin Sorry. I don't know. This seems like more of a question for the Eclipse developers who wrote the formatter, though. This project merely wraps it so the formatter can execute in a Maven build lifecycle. You may have luck seeking advice at https://bugs.eclipse.org/bugs/ or another eclipse.org forum on their website.

**Comment by jcamerin** [comment]
Thanks for all of your help @ctubbsii
