### ISSUE TITLE
KEEP line ending not working as expected, when 2.12 would release?

### ISSUE THREAD

**Issue by arpitjp** [revelc/formatter-maven-plugin#340]
Validate goal fails due to line endings even after using KEEP. Saw there was already similar issue for milestone 2.12. When would the new version release?

**Comment by ctubbsii** [comment]
@arpitjp I might be able to do a release this weekend. Ping back next week, if you don't see any activity.

**Comment by arpitjp** [comment]
Thanks, Wan't able to integrate it properly. Our team works on both windows and UNIX-like machines, and line endings was messing things up.

**Comment by tpontz** [comment]
@ctubbsii I'm also interested in 2.12.0. When will you release it?

**Comment by arpitjp** [comment]
Was able to work around line endings. What's your requirement?

**Comment by tpontz** [comment]
https://github.com/revelc/formatter-maven-plugin/pull/332

**Comment by anandvarkeyphilips** [comment]
@ctubbsii , Can we have the release soon?

**Comment by alexanderchiu** [comment]
Just ran into this issue as well. Will also be interested in a 2.12.0 release.

**Comment by hazendaz** [comment]
Soon...need to get our default JavaScript file updated and a few other odds and ends.  Maybe this weekend.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hazendaz** [comment]
Closing as this was merged.

**Comment by ctubbsii** [comment]
Thanks, @hazendaz  for taking care of the 2.12.0 release.
