### ISSUE TITLE
Inline code formatting controls not working?

### ISSUE THREAD

**Issue by jaschenk** [revelc/formatter-maven-plugin#342]
I have been trying to use the standard // @formatter:off and // @formatter:on in my code, but these formatting comments are ignored.

How can I ignore formatting ?

Please advise as this is causing havoc with a large enum class.

Thanks,
Jeff

**Comment by jeenbroekstra** [comment]
Not an expert but I had a similar issue, until I realized that you need to actually explicitly enable these tags in the code formatting settings:

      <setting id="org.eclipse.jdt.core.formatter.use_on_off_tags" value="true"/>

HTH.

**Comment by hazendaz** [comment]
This is part of the default settings now in this project.  It may not be set specificly as this but has everything.  A release will be out shortly.
