### ISSUE TITLE
Parentheses position "Preserve position" setting

### ISSUE THREAD

**Issue by jeenbroekstra** [revelc/formatter-maven-plugin#343]
I'm not sure in which version this was introduced in, but in Eclipse IDE 4.15, the formatter has options to deal with Parentheses positions.  One of the options it has is "Preserve positions" which gives the developer the freedom to choose to either put closing parentheses on a new line, or to keep them on one. 

It appears that the version the maven plugin runs on does not recognize this setting (presumably because the formatting library used is a little behind the latest eclipse release). Can you tell me what would be involved in bringing it up to date, or at least support being lenient with parentheses formatting?

**Comment by hazendaz** [comment]
We just need to cycle through all the submodules and get updated releases then we can release on 2020-06.  The default internal eclipse settings have been updated to the latest release as of today which is based off the 'eclipse' format setting with a few additional changes.  To make it easier to see updates, it's been additionally sorted.

**Comment by hazendaz** [comment]
We simply pass the configuration on to Eclipse.  If its something set in the configuration it should just work.  We are only extending eclipse in this case.  I'm getting ready to release new version up to date with latest eclipse.  Please try our current master build and see if it fixes your situation.

**Comment by jeenbroekstra** [comment]
I just found out that I probably just did something wrong on my end - apologies. I just ran another test using 2.12.0 of the plugin, and it now respects the parentheses config settings perfectly!

**Comment by hazendaz** [comment]
Great!  Thanks for letting us know all is well now.
