### ISSUE TITLE
formatter does not follow linesplit rule

### ISSUE THREAD

**Issue by Emil-Gustafsson** [revelc/formatter-maven-plugin#426]
im using the rule:
`<setting id="org.eclipse.jdt.core.formatter.lineSplit" value="120"/>`
but still some lines are formatted longer than this.
Example that will be formatted to one line:
final TransportContextModifyListItem.XxxxConfiguration xxxxConfiguration = new TransportContextModifyListItem.XxxxConfiguration();

**Comment by ctubbsii** [comment]
@Emil-Gustafsson Some Eclipse formatter rules interfere with each other and there may be exceptions (such as long import statements), and in certain cases, the Eclipse formatter will not wrap at the specified split point, if it cannot find a reasonable place to split (for example, if the line is exceeded by punctuation only, like a semicolon or parenthesis). Assignment statements are some examples of lines that won't split, without other configuration changes as well.

If this plugin is behaving the same as Eclipse with the same settings, then this is not a bug. Try importing your config into Eclipse, and exporting the full config. If you have an incomplete config, exporting the full config should fill in the missing config entries that would cause a difference in behavior via the JDT API vs. the behavior in the Eclipse JDT UI. (see discussion at https://bugs.eclipse.org/bugs/show_bug.cgi?id=545603)

**Comment by Emil-Gustafsson** [comment]
im not sure how eclipse would handle it but i used the same rules with com.googlecode.maven-java-formatter-plugin and it split the line on the linesplit rule.

**Comment by ctubbsii** [comment]
> im not sure how eclipse would handle it but i used the same rules with com.googlecode.maven-java-formatter-plugin and it split the line on the linesplit rule. But i will give it a try in eclipse

The plugin you are referring to is a very old version of this plugin, from before it moved to GitHub, and when it was using a **much** older version of Eclipse JDT (3.8) to format Java code. This plugin is much more up-to-date with the newer Eclipse JDT releases (3.24). Eclipse itself has changed its behavior a bit between 3.8 and 3.24 to support new Java language features, more granular formatting options, etc. Therefore, it is not surprising that an older config file will not work as expected.

**Comment by Emil-Gustafsson** [comment]
okey, sounds like i have to find a combination so this rule is followed.
