### ISSUE TITLE
Allow custom file extensions to help identify which formatter to use

### ISSUE THREAD

**Issue by richardwalsh** [revelc/formatter-maven-plugin#427]
It would be great if I could provide the plugin a configuration to override the default extensions that are used to identify which formatter to use.  I suppose it could go overboard with a comma separate list or regex, but for my needs it could be something as simple the following snippet:

```
<configuration>
      <jsonFileExtension>avsc</jsonFileExtension>
      <htmlFileExtension>HTM</htmlFileExtension>
</configuration>
```

The motivation for this is I want to use the plugin to reformat Avro schema definitions that are in written in json but are defined in files with the extension of ".avsc". That is a problem because the [FormatterMojo.doFormatFile()](https://github.com/revelc/formatter-maven-plugin/blob/f3926fc8db1c356a9d02b6575f7c0df23878ebfe/src/main/java/net/revelc/code/formatter/FormatterMojo.java#L607) only performs json formatting for files with the normal extension of ".json". 

Thanks

**Comment by ctubbsii** [comment]
The normal `<includes/>` and `<excludes/>` patterns like described on [the documentation](https://code.revelc.net/formatter-maven-plugin/format-mojo.html) would work well of the formatters were separated into different mojos, as described in #254 . Then, this feature wouldn't be needed.

**Comment by richardwalsh** [comment]
> The normal `<includes/>` and `<excludes/>` patterns like described in [the documentation](https://code.revelc.net/formatter-maven-plugin/format-mojo.html) would work well if the formatters were separated into different mojos, as described in #254 . Then, this feature wouldn't be needed.

Totally agree. In my case, use something like ```format-json``` and use the directory and includes/excludes to identify the candidates.

**Comment by ctubbsii** [comment]
@richardwalsh Since #254 is the preferred solution, are you okay with closing this issue for now, so that any contributors interested in creating a PR for to support this use case will focus instead on that other issue rather than this one?

**Comment by richardwalsh** [comment]
Sure that works
