### ISSUE TITLE
Sometimes the xml formatter make the xml files corrupt

### ISSUE THREAD

**Issue by martinaldrin** [revelc/formatter-maven-plugin#431]
**Describe the bug**
I added have enabled the xml formatter in our project, containing hundreds of xml file. the majority of the formatting looks good, but almost every time the formatter mess up one or more xml files. Adding allot of spaces.

Then i do undo in gerrit on all faulty xml files and then some other xml files can be corrupt.

**Versions (OS, Maven, Java, and others, as appropriate):**
lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	RedHatEnterpriseServer
Description:	Red Hat Enterprise Linux Server release 7.8 (Maipo)
Release:	7.8
Codename:	Maipo

**To Reproduce**
I Don't know.

**Expected behavior**

**Screenshots**
The screen shot shows that spaces are added on all lines.
![image](https://user-images.githubusercontent.com/3080866/108086816-14f5bc00-7077-11eb-9ea6-77b85a651971.png)

**Additional context**

**Comment by ctubbsii** [comment]
Please provide an example XML file and plugin configuration to reproduce this issue. If possible, please provide it in the form of a small sample Maven project.

**Comment by martinaldrin** [comment]
I’m not able to reproduce the fault in smaller projects. And since it affect different xml files every time, I have not figured out what triggers the fault.

**Comment by ctubbsii** [comment]
> I’m not able to reproduce the fault in smaller projects. And since it affect different xml files every time, I have not figured out what triggers the fault.

The formatter should behave consistently. If it is affecting different files every time, then there's probably something else going on, rather than this plugin. Likely culprits might be: corrupt RAM, failing hard drive, or another process (possibly an IDE or editor that is open or an anti-virus).

If it is this plugin, some information that might be helpful:

1. what does your Maven command-line look like when you execute a build?
2. is this a multi-module project?

**Comment by martinaldrin** [comment]
I don't think it is related to the hardware, since i run it in our CI. So i run on different server every time. And the rest of our CI works well.


1. 
mvn formatter:format
----- withMaven Wrapper script -----
Picked up JAVA_TOOL_OPTIONS: -Dmaven.ext.class.path="..../proj/cl1@tmp/withMavenadbbf630/pipeline-maven-spy.jar" -Dorg.jenkinsci.plugins.pipeline.maven.reportsFolder=".../proj/cl1@tmp/withMavenadbbf630" 
Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T21:00:29+02:00)
Maven home: /app/vbuild/tools/maven/3.6.1
Java version: 1.8.0_202, vendor: Oracle Corporation, runtime: .../app/vbuild/SLED11-x86_64/jdk/1.8.0_202/jre
Default locale: en_US, platform encoding: ISO-8859-1
OS name: "linux", version: "3.10.0-1127.8.2.el7.x86_64", arch: "amd64", family: "unix"
[INFO] [jenkins-event-spy] Generate ..../proj/cl1@tmp/withMavenadbbf630/maven-spy-20210216-160922-700987217794626206369.log.tmp ...
[INFO] Scanning for projects..

2.
Yes it is a multi module project with about 20 modules. we have used the java formatter for a while and that have been working fine, and this week we tried to enable the xml formatting since some users requested that.

**Comment by martinaldrin** [comment]
I can also mention that I tried following xml formatter as well, and that one does not give me this issue.  But i can not the acegi formatter since it modifies values in quotes for us. e.g replace > with &gt. 
<groupId>au.com.acegi</groupId>
<artifactId>xml-format-maven-plugin</artifactId>
<version>3.1.2</version>

**Comment by martinaldrin** [comment]
Another issue that i have seen is that not all files are formatted first time i run the command, if I rerun the command directly after it will format some more files that i guess it missed first time.

**Comment by martinaldrin** [comment]
I think i see a pattern now, the problems seems to only happen in modules where we get following warnings.
WARN: The processing instruction target matching "[xX][mM][lL]" is not allowed.

And the warning is expected on some of our xml files, since they contain raw netconf xml files. Can it be that the space indentation is not cleared correctly when we get these warnings?


```
<?xml version="1.0" encoding="UTF-8"?>

<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
    <capabilities>
        <capability>urn:ietf:params:netconf:base:1.0</capability>
        <capability>urn:com:xxx:ebase:1.1.0</capability>
    </capabilities>
</hello>
]]>]]>

```

**Comment by ctubbsii** [comment]
@martinaldrin I think your hunch that the indent depth wasn't reset on error might be correct. I found and fixed a bug in revelc/xml-formatter#41

**Comment by ctubbsii** [comment]
@martinaldrin I believe this will be fixed in 2.14.0, which should be available in a few hours in Maven Central. Please test, and let me know if this doesn't solve your problem.

**Comment by martinaldrin** [comment]
Thanks allot, it seems to be working fine now.

**Comment by aaime** [comment]
Sounds pretty similar to what I see here: https://github.com/revelc/formatter-maven-plugin/issues/433
Already using 2.14.0 there though.
