### ISSUE TITLE
XML formatting is not thread safe (parallel build support)

### ISSUE THREAD

**Issue by aaime** [revelc/formatter-maven-plugin#433]
**Describe the bug**
Trying to run the formatter to fix XML files (including the pom.xml files) on a large project (200 modules).
Given the size, a parallel build is mandatory to contain the build times, and leverage modern multi-core CPUs.
Testing the plugin, I had occasional failures, e.g.:

```
[ERROR] Failed to execute goal net.revelc.code.formatter:formatter-maven-plugin:2.14.0:format (default-cli) on project gs-web-oseo: Execution default-cli of goal net.revelc.code.formatter:formatter-maven-plugin:2.14.0:format failed: String index out of range: -2
```

Weird enough, I cannot find any stack trace. The end result is ruined XML files as well (thankfully they can be easily recovered via version control).

It turns out, even runs wtihout errors ruins the checkout, here is maven trying to build the files:

```
INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-readable POM /home/aaime/devel/git-gs-clean/src/security/pom.xml: ISO-889 @ 
[FATAL] Non-readable POM /home/aaime/devel/git-gs-clean/src/wcs/pom.xml: ISO-889 @ 
[FATAL] Non-parseable POM /home/aaime/devel/git-gs-clean/src/wcs2_0/pom.xml: Unrecognised tag: 'groupImodelVersion' (position: START_TAG seen ...</parent>\n\n\t<groupImodelVersion>... @17:22)  @ line 17, column 22
[FATAL] Non-parseable POM /home/aaime/devel/git-gs-clean/src/wms/pom.xml: end tag name </a> must match start tag name <artifactId> from line 172 (position: TEXT seen ...<artifactId>hamcrest-library</a\r... @172:36)  @ line 172, column 36
[FATAL] Non-parseable POM /home/aaime/devel/git-gs-clean/src/kml/pom.xml: unexpected character in markup 4 (position: START_TAG seen ...apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">\n<4... @7:3)  @ line 7, column 3
[FATAL] Non-parseable POM /home/aaime/devel/git-gs-clean/src/rest/pom.xml: Unrecognised tag: 'groupId' (position: START_TAG seen ...<!-- Test dependencies -->\n\t\t\n\t\t\t<groupId>... @31:13)  @ line 31, column 13
[FATAL] Non-parseable POM /home/aaime/devel/git-gs-clean/src/restconfig/pom.xml: expected START_TAG or END_TAG not TEXT (position: TEXT seen ...</artifactId>\nversion>${project.version}</... @46:29)  @ line 46, column 29
[FATAL] Non-parseable POM /home/aaime/devel/git-gs-clean/src/web/app/pom.xml: markup not allowed inside attribute value - illegal <  (position: TEXT seen ...<beans xmlns="http://www.springframework.orupId>\n          <... @477:12)  @ line 477, column 12
[FATAL] Non-parseable POM /home/aaime/devel/git-gs-clean/src/web/wms/pom.xml: markup not allowed inside attribute value - illegal <  (position: TEXT seen ...eflector" class="org.geoserver.kml.WebMapServicegroupId>    \n    <... @14:6)  @ line 14, column 6
[FATAL] Non-parseable POM /home/aaime/devel/git-gs-clean/src/web/wfs/pom.xml: expected = after attribute name (position: START_DOCUMENT seen ...id="rdeCoveraeorePanel" classroserver.web.data.resce.DatStrePaneo"... @7:74)  @ line 7, column 74
[FATAL] Non-parseable POM /home/aaime/devel/git-gs-clean/src/web/gwc/pom.xml: end tag name </roupId> must match start tag name <scope> from line 69 (position: TEXT seen ...<scope>test</roupId>... @69:24)  @ line 69, column 24
[FATAL] Non-parseable POM /home/aaime/devel/git-gs-clean/src/web/security/core/pom.xml: markup not allowed inside attribute value - illegal <  (position: TEXT seen ...<project xmlns="http://maven.apache.orgaent>\n\t\t<... @13:4)  @ line 13, column 4
[FATAL] Non-parseable POM /home/aaime/devel/git-gs-clean/src/web/security/jdbc/pom.xml: unexpected character in markup \n (position: START_TAG seen ...<parent>\n\t\t<groupId>org.geoserver.web<\n... @14:1)  @ line 14, column 1
[FATAL] Non-parseable POM /home/aaime/devel/git-gs-clean/src/web/security/ldap/pom.xml: expected START_TAG or END_TAG not TEXT (position: TEXT seen ...<groupId>org.geoservemr.web</groupId>\nartifactId>gs-web-sec-core</... @26:29)  @ line 26, column 29
[FATAL] Non-parseable POM /home/aaime/devel/git-gs-clean/src/community/pom.xml: expected > to end empty tag not x (position: TEXT seen ...</descriptor>\n\t\t\t\t\t\t<bees/x... @74:14)  @ line 74, column 14
[FATAL] Non-parseable POM /home/aaime/devel/git-gs-clean/src/extension/pom.xml: in comment after two dashes (--) next character must be > not p (position: START_DOCUMENT seen <?xml version="1.0" encoding="ISO-8859-1"?>\n<!-- \n Copyr<--p... @3:11)  @ line 3, column 11
 @ 
[ERROR] The build could not read 16 projects -> [Help 1]
[ERROR]   
[ERROR]   The project  (/home/aaime/devel/git-gs-clean/src/security/pom.xml) has 1 error
[ERROR]     Non-readable POM /home/aaime/devel/git-gs-clean/src/security/pom.xml: ISO-889
[ERROR]   
[ERROR]   The project  (/home/aaime/devel/git-gs-clean/src/wcs/pom.xml) has 1 error
[ERROR]     Non-readable POM /home/aaime/devel/git-gs-clean/src/wcs/pom.xml: ISO-889
[ERROR]   
[ERROR]   The project  (/home/aaime/devel/git-gs-clean/src/wcs2_0/pom.xml) has 1 error
[ERROR]     Non-parseable POM /home/aaime/devel/git-gs-clean/src/wcs2_0/pom.xml: Unrecognised tag: 'groupImodelVersion' (position: START_TAG seen ...</parent>\n\n\t<groupImodelVersion>... @17:22)  @ line 17, column 22 -> [Help 2]
[ERROR]   
[ERROR]   The project  (/home/aaime/devel/git-gs-clean/src/wms/pom.xml) has 1 error
[ERROR]     Non-parseable POM /home/aaime/devel/git-gs-clean/src/wms/pom.xml: end tag name </a> must match start tag name <artifactId> from line 172 (position: TEXT seen ...<artifactId>hamcrest-library</a\r... @172:36)  @ line 172, column 36 -> [Help 2]
[ERROR]   
[ERROR]   The project  (/home/aaime/devel/git-gs-clean/src/kml/pom.xml) has 1 error
[ERROR]     Non-parseable POM /home/aaime/devel/git-gs-clean/src/kml/pom.xml: unexpected character in markup 4 (position: START_TAG seen ...apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">\n<4... @7:3)  @ line 7, column 3 -> [Help 2]
[ERROR]   
[ERROR]   The project  (/home/aaime/devel/git-gs-clean/src/rest/pom.xml) has 1 error
[ERROR]     Non-parseable POM /home/aaime/devel/git-gs-clean/src/rest/pom.xml: Unrecognised tag: 'groupId' (position: START_TAG seen ...<!-- Test dependencies -->\n\t\t\n\t\t\t<groupId>... @31:13)  @ line 31, column 13 -> [Help 2]
[ERROR]   
[ERROR]   The project  (/home/aaime/devel/git-gs-clean/src/restconfig/pom.xml) has 1 error
[ERROR]     Non-parseable POM /home/aaime/devel/git-gs-clean/src/restconfig/pom.xml: expected START_TAG or END_TAG not TEXT (position: TEXT seen ...</artifactId>\nversion>${project.version}</... @46:29)  @ line 46, column 29 -> [Help 2]
[ERROR]   
[ERROR]   The project  (/home/aaime/devel/git-gs-clean/src/web/app/pom.xml) has 1 error
[ERROR]     Non-parseable POM /home/aaime/devel/git-gs-clean/src/web/app/pom.xml: markup not allowed inside attribute value - illegal <  (position: TEXT seen ...<beans xmlns="http://www.springframework.orupId>\n          <... @477:12)  @ line 477, column 12 -> [Help 2]
[ERROR]   
[ERROR]   The project  (/home/aaime/devel/git-gs-clean/src/web/wms/pom.xml) has 1 error
[ERROR]     Non-parseable POM /home/aaime/devel/git-gs-clean/src/web/wms/pom.xml: markup not allowed inside attribute value - illegal <  (position: TEXT seen ...eflector" class="org.geoserver.kml.WebMapServicegroupId>    \n    <... @14:6)  @ line 14, column 6 -> [Help 2]
[ERROR]   
[ERROR]   The project  (/home/aaime/devel/git-gs-clean/src/web/wfs/pom.xml) has 1 error
[ERROR]     Non-parseable POM /home/aaime/devel/git-gs-clean/src/web/wfs/pom.xml: expected = after attribute name (position: START_DOCUMENT seen ...id="rdeCoveraeorePanel" classroserver.web.data.resce.DatStrePaneo"... @7:74)  @ line 7, column 74 -> [Help 2]
[ERROR]   
[ERROR]   The project  (/home/aaime/devel/git-gs-clean/src/web/gwc/pom.xml) has 1 error
[ERROR]     Non-parseable POM /home/aaime/devel/git-gs-clean/src/web/gwc/pom.xml: end tag name </roupId> must match start tag name <scope> from line 69 (position: TEXT seen ...<scope>test</roupId>... @69:24)  @ line 69, column 24 -> [Help 2]
[ERROR]   
[ERROR]   The project  (/home/aaime/devel/git-gs-clean/src/web/security/core/pom.xml) has 1 error
[ERROR]     Non-parseable POM /home/aaime/devel/git-gs-clean/src/web/security/core/pom.xml: markup not allowed inside attribute value - illegal <  (position: TEXT seen ...<project xmlns="http://maven.apache.orgaent>\n\t\t<... @13:4)  @ line 13, column 4 -> [Help 2]
[ERROR]   
[ERROR]   The project  (/home/aaime/devel/git-gs-clean/src/web/security/jdbc/pom.xml) has 1 error
[ERROR]     Non-parseable POM /home/aaime/devel/git-gs-clean/src/web/security/jdbc/pom.xml: unexpected character in markup \n (position: START_TAG seen ...<parent>\n\t\t<groupId>org.geoserver.web<\n... @14:1)  @ line 14, column 1 -> [Help 2]
[ERROR]   
[ERROR]   The project  (/home/aaime/devel/git-gs-clean/src/web/security/ldap/pom.xml) has 1 error
[ERROR]     Non-parseable POM /home/aaime/devel/git-gs-clean/src/web/security/ldap/pom.xml: expected START_TAG or END_TAG not TEXT (position: TEXT seen ...<groupId>org.geoservemr.web</groupId>\nartifactId>gs-web-sec-core</... @26:29)  @ line 26, column 29 -> [Help 2]
[ERROR]   
[ERROR]   The project  (/home/aaime/devel/git-gs-clean/src/community/pom.xml) has 1 error
[ERROR]     Non-parseable POM /home/aaime/devel/git-gs-clean/src/community/pom.xml: expected > to end empty tag not x (position: TEXT seen ...</descriptor>\n\t\t\t\t\t\t<bees/x... @74:14)  @ line 74, column 14 -> [Help 2]
[ERROR]   
[ERROR]   The project  (/home/aaime/devel/git-gs-clean/src/extension/pom.xml) has 1 error
[ERROR]     Non-parseable POM /home/aaime/devel/git-gs-clean/src/extension/pom.xml: in comment after two dashes (--) next character must be > not p (position: START_DOCUMENT seen <?xml version="1.0" encoding="ISO-8859-1"?>\n<!-- \n Copyr<--p... @3:11)  @ line 3, column 11 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/ModelParseException
```

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Affected version(s) of this project: 2.14.0
 - OS: Linux Mint
 - Others: 

**To Reproduce**
Steps to reproduce the behavior (or a link to an example repository that reproduces the problem):
1. Checkout this branch: https://github.com/aaime/geoserver/tree/eclipse_xml_formatter
2. Back out the formatting changes, keeping only the formatter setup: ``git reset --hard HEAD^``
3. ``cd src``
4. Run the formatter on all projects, with a parallel build: ``mvn formatter:format -T4 -Prelease,communityRelease``
5. Watch the fireworks start

**Expected behavior**
All of the xml files should be properly formatted.

**Comment by ctubbsii** [comment]
@aaime Does the same issue occur if you build it as part of a build lifecycle, rather than as a standalone goal execution?

For example: `mvn validate formatter:format -T4 -Prelease,communityRelease` or `mvn package formatter:format -T4 -Prelease,communityRelease`?

**Comment by aaime** [comment]
Validate is pretty fast and fails right away, same `` String index out of range: -2`` failure reported above.

Package is pretty slow instead, it does more, like compiling and would even run the tests. I made it a bit faster by skipping the tests: ``mvn package formatter:format -T4 -Prelease,communityRelease -nsu -fae -DskipTests``
This one got to the end, but the pom files are ruined like in my second example.

**Comment by ctubbsii** [comment]
@aaime It doesn't matter if it's `package` or `validate` or another goal in the maven lifecycle. The main point is that there's often a difference in behavior between running a plugin as part of [a build lifecycle](https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html) (`mvn <lifecyclegoal> otherplugin:goal`) vs. as standalone (`mvn otherplugin:goal`).

I'm having trouble reproducing this either way. Can you create a sample repository that reproduces the problem? Or point me to a public one where it occurs?

Also, I noticed you're using this plugin for formatting `pom.xml` files. Please note that this plugin is not as good as other plugins that are more well-suited for `pom.xml` files. Specifically, I recommend using the [`sortpom-maven-plugin`](https://github.com/Ekryd/sortpom), which not only does the XML formatting, it also standardizes the POM sections, sorts and groups dependencies by scope and groupId, etc. It's much better than this plugin, which has only basic XML formatting.

**Comment by hazendaz** [comment]
@aaime The change you have in your configuration with sourceDirectory and the excepted behaviour of includes is incorrect.  Doing that setup, it tells it to include all poms in the run parent module.  The underlying then are also included on underlying jobs so its running multiple times as a result.  You really want to keep it at the default source directory of src (ie ${project.build.sourceDirectory}) as it blocks its abilty to drop into child modules.  The includes is X number of matches rather than specific file in specific folder (its recursive).  For formatting poms, you would rather want to use 'sortpom-maven-plugin' as it not only formats but can enforce maven layout rules that this plugin would never address.

**Comment by ctubbsii** [comment]
You could also try to only run it at the root of your project, and not let it get inherited to child modules: https://stackoverflow.com/a/46357305/196405

**Comment by aaime** [comment]
So I guess I could use revelc to format the Spring application context files, but would have to use another plugin for the poms? 

@hazendaz so by telling ``pom.xml`` in the includes, it's actually picking the pom files of all children? Odd, I though I would have had to add a ``**/pom.xml`` include for it to pick the children's pom files too. 
But even if it did, it should not be processing parent and child at the same time... or does it?

I'll have a look at sortpom. Did not stumble into it before. In GeoServer we were also experimenting with the acegi xml formatter, but not to thrilled about results (eats white lines): https://github.com/geoserver/geoserver/pull/4663

**Comment by aaime** [comment]
@ctubbsii I'd need something that works transparently like the google-java format plugin we alredy have does (but, for XML files): it can be run along with the build of a module, or a group of module, of the entire project, sequential, parallel, or called directly.

**Comment by hazendaz** [comment]
As this is expected to pick up many files, the ** wasn't considered for how that works years ago.  I activiley use both in many projects (sortpom for poms) and this for normal processing.  Works really well.  I also tried acegi xml formatter a few years back.  Same issue you experienced there.  That is sort of how this plugin evolved to handle xml.

As to running at same time.  Part of the parent is running the moment its started.  So that is the issue I believe. I also tried as you did previously and saw the issue but couldn't figure a good way around it, but I had not tried as @ctubbsii noted to skip inheritence.  That may work as well.

sortpom is here -> https://github.com/Ekryd/sortpom  It is as good as it gets for maven.  Very little configuration is needed on it to work basically like your formatting is likely already setup and it can be customized for different rules you might ultimately use.

**Comment by hazendaz** [comment]
In fact, if I recall, this project is likely using sortpom as well in its build files as an example.

**Comment by aaime** [comment]
> In fact, if I recall, this project is likely using sortpom as well in its build files as an example.

It does indeed: https://github.com/revelc/formatter-maven-plugin/blob/main/pom.xml#L513

**Comment by ctubbsii** [comment]
Using `<inherited>false</inherited>` won't work for this case, since that only prevents inheriting the config. If the `formatter:format` is specified on the command-line, it will still execute... just without the inherited config. That strategy would only work if the execution itself was also defined in the plugin config, and not on the command-line.

**Comment by ctubbsii** [comment]
I think ultimately, the problem is that this configuration in the `pom.xml` is specifying patterns that conflict when the plugin is executed in both a parent and a child module in the multi-module build in separate threads. It might be possible to bake in protection in those cases, but it'd probably be better to execute the plugin correctly, so that each execution only operated on files in its own module, and not recursed into sub-modules, with a separate execution.

**Comment by ctubbsii** [comment]
For what it's worth, I attempted to create a per-file locking mechanism to prevent the plugin from operating on the same file by more than one thread at the same time, and it didn't seem to help. It's possible that my implementation didn't work because the class is loaded with separate classloaders by Maven, so the different threads didn't see the same static map of per-file locks.

**Comment by aaime** [comment]
I was thinking, "ok, let's try sortpom and use revelc for the other files". But, turns out, some of the files I'd like to format are the assembly descriptors, which happen to also be found in the two release modules root:
* https://github.com/geoserver/geoserver/tree/master/src/release (supported plugins)
* https://github.com/geoserver/geoserver/tree/master/src/community/release (unsupported plugins)

I'm back to square one am I not? :-D
Guess to use the formatter, I'd have to move those descriptors somewhere else, like in ``src/main/resources``

**Comment by ctubbsii** [comment]
> Guess to use the formatter, I'd have to move those descriptors somewhere else, like in `src/main/resources`

They don't have to go in `src/main/resources`, because that's most often used for adding stuff to a jar that isn't a `.class` file, and you probably don't want those showing up in your jars. However, it would probably be a good idea to put them in a subdirectory. In general, you should try to use the [standard Maven directory layout](https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html) whenever using Maven. You'll have less problems with assumptions that various plugins make.

**Comment by ctubbsii** [comment]
So, I tried to modify the formatter to write files out in an atomic way using temporary files and then an atomic move/overwrite. It didn't work. I'm really not sure what could be causing this file corruption.

**Comment by aaime** [comment]
So I've given up using this plugin on pom files, and giving sortpom a try instead.
I still want to format the Spring context files, and it needs to work in a parallel build (project size, all builds are parallelized, in GitHub actions, Jenkins jobs, and local builds).

The configuration has been modified as follows:

```
      <plugin>
        <groupId>net.revelc.code.formatter</groupId>
        <artifactId>formatter-maven-plugin</artifactId>
        <version>2.14.0</version>
        <configuration>
          <skipFormatting>${xml.fmt.skip}</skipFormatting>
          <skipCssFormatting>true</skipCssFormatting>
          <skipHtmlFormatting>true</skipHtmlFormatting>
          <skipJavaFormatting>true</skipJavaFormatting>
          <skipJsFormatting>true</skipJsFormatting>
          <skipJsonFormatting>true</skipJsonFormatting>
          <skipXmlFormatting>false</skipXmlFormatting>
          <configXmlFile>${geoserverBaseDir}/../build/qa/xml-format.properties</configXmlFile>
          <encoding>UTF-8</encoding>
          <includes>
            <include>application*Context.xml</include>
          </includes>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>${xml.fmt.action}</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
```

I'm assuming this should work inside ``src``, which theoretically, should prevent the plugin from formatting the same file twice in the same build. However, it's still failing:

```
[ERROR] Failed to execute goal net.revelc.code.formatter:formatter-maven-plugin:2.14.0:format (default-cli) on project gs-web-sec-core: Execution default-cli of goal net.revelc.code.formatter:formatter-maven-plugin:2.14.0:format failed: String index out of range: -2 -> [Help 1]
[ERROR] Failed to execute goal net.revelc.code.formatter:formatter-maven-plugin:2.14.0:format (default-cli) on project gs-wms: Execution default-cli of goal net.revelc.code.formatter:formatter-maven-plugin:2.14.0:format failed: String index out of range: -2 -> [Help 1]
[ERROR] 
```

I've updated the PR in GeoServer with the new config, if you want, you can check it out to double check the issue:
https://github.com/geoserver/geoserver/pull/4800

**Comment by ctubbsii** [comment]
@aaime I can try to take a look sometime next week. However, it may be useful to have a stack trace of the error. You can get the stack trace by running Maven with the `-e` flag (or `-X` to get the full debug messages).

**Comment by aaime** [comment]
Here is the stack trace:

```
[ERROR] Failed to execute goal net.revelc.code.formatter:formatter-maven-plugin:2.14.0:format (default-cli) on project gs-web-core: Execution default-cli of goal net.revelc.code.formatter:formatter-maven-plugin:2.14.0:format failed: String index out of range: -2 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal net.revelc.code.formatter:formatter-maven-plugin:2.14.0:format (default-cli) on project gs-web-core: Execution default-cli of goal net.revelc.code.formatter:formatter-maven-plugin:2.14.0:format failed: String index out of range: -2
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:190)
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:186)
    at java.util.concurrent.FutureTask.run (FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:511)
    at java.util.concurrent.FutureTask.run (FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
    at java.lang.Thread.run (Thread.java:748)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal net.revelc.code.formatter:formatter-maven-plugin:2.14.0:format failed: String index out of range: -2
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:148)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:190)
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:186)
    at java.util.concurrent.FutureTask.run (FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:511)
    at java.util.concurrent.FutureTask.run (FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
    at java.lang.Thread.run (Thread.java:748)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -2
    at java.lang.String.charAt (String.java:658)
    at net.revelc.code.formatter.xml.lib.XMLTagFormatter$TagParser.isClosed (XMLTagFormatter.java:355)
    at net.revelc.code.formatter.xml.lib.XMLTagFormatter$TagParser.parse (XMLTagFormatter.java:365)
    at net.revelc.code.formatter.xml.lib.XMLTagFormatter.format (XMLTagFormatter.java:34)
    at net.revelc.code.formatter.xml.lib.XmlDocumentFormatter.copyNode (XmlDocumentFormatter.java:78)
    at net.revelc.code.formatter.xml.lib.XmlDocumentFormatter.format (XmlDocumentFormatter.java:103)
    at net.revelc.code.formatter.xml.XMLFormatter.doFormat (XMLFormatter.java:59)
    at net.revelc.code.formatter.AbstractCacheableFormatter.formatFile (AbstractCacheableFormatter.java:52)
    at net.revelc.code.formatter.FormatterMojo.doFormatFile (FormatterMojo.java:605)
    at net.revelc.code.formatter.FormatterMojo.formatFile (FormatterMojo.java:531)
    at net.revelc.code.formatter.FormatterMojo.execute (FormatterMojo.java:402)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:190)
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:186)
    at java.util.concurrent.FutureTask.run (FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:511)
    at java.util.concurrent.FutureTask.run (FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
    at java.lang.Thread.run (Thread.java:748)
```

**Comment by ctubbsii** [comment]
@jam01 Do you know what's going on with the xml-formatter in the above stack trace?

**Comment by aaime** [comment]
@hazendaz if we want to discuss issues of the eclipseformatter-maven-plugin under parallel buids, let's do it here.

To summarize a bit of the above, I've given up formatting pom files and switched to sortpom on them, the PR has been updated to only try to format the application context files, a parallel build involving 200+ modules still fails, failing on different modules at every run. The funny thing, after retrying a few times, it stopped failing (I clean up the checkout at every run)... then I switched from java 11 to java 8, re-run, it failed, and then it did not anymore.

**Comment by jam01** [comment]
It's been a while since I was deep into the workings of the formatter, but I can't see anything that screams 'unsafe to parallelize]. 

The error basically means that an XML node was recognized (found an `<`) and characters were consumed until a `>` was found, or the string ran out. When it tried to format the node (`< ... >`) it couldn't find an `>`. 

Given that subsequent runs succeed I'm thinking the issue may not be with the xml-formatter logic but maybe with the reading of the file before hand? Perhaps files are not being read in their entirety somehow? Turning on well formedness validation might give us another clue or confirmation that the file contents are sometimes not read correctly. Otherwise a way to reproduce the issue would be necessary to further debug.

**Comment by aaime** [comment]
@jam01 how do I turn on validation? I can't find a page enumerating the options for the xml formatter.

The configuration file I currently have is here:
https://github.com/geoserver/geoserver/pull/4800/files#diff-f6498acc0e4c272ca0cb3b54f073d4b545635e4c3d27b01c84add6b3acaa28caR1

Not sure if all the options are correct, the documentation seemed to suggest it was usign the Eclipse XML formatter, learned that it's a home grown one reading the discussion here.

Hmm... been checking the sources of the xml formatter, I guess it's ``wellFormedValidation=FAIL`` based on https://github.com/revelc/xml-formatter/blob/main/src/main/java/net/revelc/code/formatter/xml/lib/FormattingPreferences.java#L28

**Comment by aaime** [comment]
Ok so I switched the setting to "FAIL", rebooted to get a better chance to reproduce, and got... the same result as before :-D

```
[ERROR] Failed to execute goal net.revelc.code.formatter:formatter-maven-plugin:2.14.0:format (default-cli) on project gs-web-core: Execution default-cli of goal net.revelc.code.formatter:formatter-maven-plugin:2.14.0:format failed: String index out of range: -2 -> [Help 1]
[ERROR] Failed to execute goal net.revelc.code.formatter:formatter-maven-plugin:2.14.0:format (default-cli) on project gs-wfs: Execution default-cli of goal net.revelc.code.formatter:formatter-maven-plugin:2.14.0:format failed: String index out of range: -2 -> [Help 1]
```

The GeoServer branch with the formatter configured has been updated with the config change:
https://github.com/aaime/geoserver/tree/eclipse_xml_formatter

**Comment by aaime** [comment]
Scanning throught the XML formatter code I noticed this bit, which does not look thread safe:

https://github.com/revelc/xml-formatter/blob/main/src/main/java/net/revelc/code/formatter/xml/lib/XmlDocumentFormatter.java#L293

The readers there are static, the text reader too, but just a few lines below the code for the TextReader seems stateful, has a "complete" and a "isTextNode" field. Other readers look stateful too. Maybe the factory should instatiate them, or if it's important to cache them, keep a thread local cache of them, to be cleaned up once the format of a given file is done?

**Comment by jam01** [comment]
You're right! Those are not thread safe. I looked at them last night, but I guess my brain wasn't thread safe itself then. I'll take a quick stab at this, Would running this locally reproduce the issue?

```
    - name: Build with Maven
      run: mvn -B -U -T3 -fae -Dfmt.skip=true -Prelease -f src/pom.xml clean install
```

**Comment by aaime** [comment]
I have updated the branch so that it contains a little bash script that reformats and resets over and over:
https://github.com/aaime/geoserver/blob/eclipse_xml_formatter/src/format_loop.sh

I has to run a number of times to fail on my machine... but it loops a hundred :-D
If you're not on a *nix OS, guess you can put toghether something similar, and tweak it.

**Comment by jam01** [comment]
@aaime the changes in the draft pull request address the issue in my local runs. Can you confirm the same? You'd have to pull that branch and `mvn install` then add a dependency to the plug-in in your project's pom pointing to xml-formatter:0.3.0-SNAPSHOT

**Comment by aaime** [comment]
@jam01 tried it out (usage of the snapshots versions is indeed required for both xml-formatter and formatter-maven-plugin btw).
I cannot reproduce the issue any longer, seems to be formatting the code!
