### ISSUE TITLE
Let's cut the luna release

### ISSUE THREAD

**Issue by hazendaz** [revelc/formatter-maven-plugin#44]
I don't have much time to work on this currently.  Now that things have been rearranged and under new guidence, I don't know that we need to wait to cut the luna release.  I'd prefer to get this released so we have something solid there then move on to Mars.  If no issues and you have time, cut the release.  Or I can later this week.

**Comment by velo** [comment]
FWIW, I just did a 1.6.0.RC1 on mars.... luna is on my fork since 1.4.0

**Comment by hazendaz** [comment]
@velo let's try this.  I'd like to release this library as is for Luna track.  Then I'd like to start getting your changes which I believe will take a awhile.  In the meantime can you provide usage statistics on you repo from central on unique Ip addresses for last few months? By then i suspect some statistics here.  I'm curious how many people are following original and your repo plus what that would bring us as we try to merge bases.

--- Original Message ---

**Comment by hazendaz** [comment]
I have cut a release.  There were a couple of minor issues getting the site deployment right.  That said, the release was cut as 0.5.2.  Now we can focus on trying to merge the code bases with @velo

**Comment by ctubbsii** [comment]
Out of curiosity, I also see 0.5 and 0.5.1. What's with those?

**Comment by hazendaz** [comment]
Site deploy failed and maven release doesn't remove scm tags on revert.  There are work arounds but I wanted to get it fixed.  So just pressed forwards.  In the end the builds all worked and sonatype had all three but at that point I felt it was just safer to drop the earlier ones.

--- Original Message ---

**Comment by hazendaz** [comment]
I see issue tracking being used as a change log.  I saw that once before on another project.  Do you know if there is a way to tie into that for a site report so we can delete the manual change log?  I like the concept...

--- Original Message ---

**Comment by hazendaz** [comment]
Or maybe you were just assigning me on the PRs.  Hard to tell on my phone...

--- Original Message ---

**Comment by ctubbsii** [comment]
I was mainly just playing around with the github features for bookkeeping on issues already completed (PRs included, since they are treated like issues). I'm sure there's a way to generate a report from them for the site. I'm not a fan of manual change logs at all. That's what git is for, after all. Github also has a release notes feature I haven't looked at yet.
