### ISSUE TITLE
Add ability to organize imports

### ISSUE THREAD

**Issue by ctubbsii** [revelc/formatter-maven-plugin#51]
Code formatting leaves the import ordering more or less arbitrary. Organizing these would be a big help.

**Comment by hazendaz** [comment]
mars.1 has issue where it has inability to retain organizing order.  It resets on each restart.  This is something to think about if we figure this one out as it could be confusing.  It would be nice though that we could enforce some sort of alphabetical organization as that is what is done in intellij.  Nothing really says we have to use eclipse way either.

**Comment by seratch** [comment]
:+1: If this feature is provided, it would be really helpful for me.

**Comment by ctubbsii** [comment]
I'm closing this issue as out of scope, because the Eclipse plugin that this formatter is based on does not include this feature. However, I am working on a similar plugin over in [revelc/impsort-maven-plugin][1].

[1]: https://github.com/revelc/impsort-maven-plugin
