### ISSUE TITLE
Allow trailing whitespace to trimmed

### ISSUE THREAD

**Issue by jamezp** [revelc/formatter-maven-plugin#520]
Allow the trailing whitespace to be trimmed for files. 

Add a parameter which can be switched on to trim trailing whitespace on lines. A use-case would be when you want to use this in conjunction with a checkstyle which doesn't allow trailing spaces.

**Comment by hazendaz** [comment]
In eclipse they have that on code cleanup rather than formatting.  Here is a plugin that does this now https://github.com/dantwining/whitespace-maven-plugin/.
