### ISSUE TITLE
1.8 JVM compatibility regression

### ISSUE THREAD

**Issue by therealryan** [revelc/formatter-maven-plugin#547]
**Describe the bug**
Versions 2.17.0+ of the plugin no longer work on 1.8 JVMs. If this is intentional it'd be great to have it documented.

**Versions (OS, Maven, Java, and others, as appropriate):**
 - plugin 2.17.1 and 2.17.0
 - Maven version 3.5.0
 - java version 1.8.0_301

**To Reproduce**
Run `mvn formatter:format`

**Expected behavior**
The formatter runs

**Screenshots**

```
[ERROR] Failed to execute goal net.revelc.code.formatter:formatter-maven-plugin:2.17.1:validate (default) on project parent: Execution default of goal net.revelc.code.formatter:formatter-maven-plugin:2.17.1:validate failed: Unable to load the mojo 'validate' in the plugin 'net.revelc.code.formatter:formatter-maven-plugin:2.17.1' due to an API incompatibility: org.codehaus.plexus.component.repository.exception.ComponentLookupException: net/revelc/code/formatter/ValidateMojo has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

**Additional context**
N/A

**Comment by hazendaz** [comment]
This is not an issue.  This plugin is based on Eclipse binaries.  Eclipse moved to jdk 11.  Therefore 2.17.0+ requires jdk 11 now.

**Comment by hazendaz** [comment]
@therealryan Sorry documentation is not up yet.  It was done but is held back on my end due to jsoup pending update.  I'll look at bringing that forwards today.  Thanks.

**Comment by hazendaz** [comment]
@therealryan Ok README now notes jdk 11 requirement, change log shows that as well and further adds some recently added items that were missed.  The site page was also updated to note jdk 11 requirement for clarity and will show up with our next release which likely will be soon given Eclipse just released 2021-12 today.
