### ISSUE TITLE
Format the project with the formatter

### ISSUE THREAD

**Issue by hazendaz** [revelc/formatter-maven-plugin#59]
One big thing that keeps jumping out at me is use of tabs exensively here.  In more modern coding styles that is adviced against.  However, that got me thinking, let's format ourselves with the formatter.  This just requires we use the prior version to do so.  Sort of chicken and egg but would be nice.

If need be, we can add excludes for our internal testing that needs incorrectly formatted classes.  This will be more important once we figure out XML formatting.

**Comment by velo** [comment]
+1

I think we should format all git history as well...  to prevent huge diffs caused only by format

**Comment by ctubbsii** [comment]
Re: "I think we should format all git history as well"

Please don't rewrite the history with formatting changes. That would be... very anti-git, and would confuse any attempt to merge existing outstanding work.

A huge diff is perhaps a bit annoying, but it's much more friendly than the alternative.

**Comment by velo** [comment]
The problem I see with the huge diff is that it kills history....

When you need/wanna understand why a change was introduced you wont get the information (at least not in a easy way)

**Comment by ctubbsii** [comment]
Understood, but rewriting history is not the answer. A commit which only changes formatting, and introduces no other change, is preferable. It's unfortunate that in some cases, it may make history harder to understand, but the effect is localized, limited in scope and in time. I've used this formatter plugin to reformat other projects in a single commit, and it has rarely been disruptive to the point where history could not be understood. This risk is minimal, and far preferred over the side-effect problems of rewriting history. That's my opinion, anyway.

**Comment by velo** [comment]
I wonder, what is the rewriting history side-effect?

I ask cause I'm about to do it for the ninth time =D

**Comment by ctubbsii** [comment]
The main problem is that you can't tell if a branch has already been merged, and it makes it difficult to merge cleanly back into a clone. It creates new history, which separates clones from each other, and makes it difficult to see their common ancestor (fork point). When merging, it can reintroduce the same commits, resulting in duplicates.

If you, and everybody who collaborates with you always use rebase, it's not that bad, but it can confuse rebase because of the difficulty of finding the merge-base.

It also breaks any links directly to a commit, and disassociates the tag history from the branch history.

**Comment by ctubbsii** [comment]
It's less important if you do it in your own clone/repos, but if you do it in a repository shared by or used by others, it is quite terrible.

**Comment by velo** [comment]
I see

**Comment by velo** [comment]
what is our default code formatter?
https://github.com/revelc/formatter-maven-plugin/blob/master/src/test/resources/sample-config.xml ?

or something else?

**Comment by velo** [comment]
Made a PR for it.

For start, is just eclipse vanilla formatter

Do you guys agree on that?

https://github.com/revelc/formatter-maven-plugin/pull/65

**Comment by velo** [comment]
Also, made another PR regarding pom.xml format/order

https://github.com/revelc/formatter-maven-plugin/pull/66/files

**Comment by velo** [comment]
Fixed
