### ISSUE TITLE
please release 2.18.0 to maven central

### ISSUE THREAD

**Issue by XenoAmess** [revelc/formatter-maven-plugin#605]
![image](https://user-images.githubusercontent.com/17455337/156881518-fa38b161-808c-4b05-a917-58e4dd008368.png)

I see version already be 2.19.0-SNAPSHOT in pom.

Seems you forgot to publish 2.18.0 to maven central?

**Comment by hazendaz** [comment]
@XenoAmess It is published.  Central is the index and has issues sometimes.  You can pull it though from sonatype as it is there.

See [here](https://repo1.maven.org/maven2/net/revelc/code/formatter/formatter-maven-plugin/2.18.0/)

**Comment by ctubbsii** [comment]
Yeah, it's definitely there. It may take awhile before it shows up in the search results, but it does resolve when you download it.
