### ISSUE TITLE
velo-merge -> jdk usage

### ISSUE THREAD

**Issue by hazendaz** [revelc/formatter-maven-plugin#61]
Since 0.2, master included ability to override what comes in the configuration files for jdk info.  Not sure if that was removed on velo branch or something we really need.  Opening this to just not the difference.

**Comment by velo** [comment]
Not sure what you mean?
is it this:
https://github.com/revelc/formatter-maven-plugin/blob/velo-merge/maven-plugin/src/main/java/net/revelc/code/formatter/FormatterMojo.java#L153

Can you point me out to a sample?

**Comment by hazendaz** [comment]
Original code since version 0.2 allows use of jdk settings on maven as override to what is in the format file.  I'll grab a snippet of the code tomorrow.  I'm not sure it's even needed but wanted to note it.  I've never really messed with the configuration in that way.  Currently this branch just picks that up if it cannot find a configuration file.  That may be good enough but might matter if we get source cleanup working.


Sent by Outlook for Android





On Tue, Aug 4, 2015 at 7:57 PM -0700, "Marvin Froeder" <notifications@github.com> wrote:
Not sure what you mean?
is it this:
https://github.com/revelc/formatter-maven-plugin/blob/velo-merge/maven-plugin/src/main/java/net/revelc/code/formatter/FormatterMojo.java#L153

Can you point me out to a sample?

---

**Comment by ctubbsii** [comment]
I use that feature, and would like to keep it, if we can.

**Comment by velo** [comment]
we sure can.... I'm just not sure what is missing, can you point out the code o master for me?

**Comment by ctubbsii** [comment]
One other suggestion: it could be helpful if you guys use the labels, milestones, and assignees, in GitHub to organize issues/pull requests so they can be searched/tracked later. This might be slightly more useful than topic prefixes in the title (e.g. "velo-merge ->"), in the case of labels, and better than trying to find the commits in the git history, in the case of milestones.

**Comment by hazendaz** [comment]
Sounds good.  Thanks


Sent by Outlook for Android





On Thu, Aug 6, 2015 at 10:52 AM -0700, "Christopher Tubbs" <notifications@github.com> wrote:
One other suggestion: it could be helpful if you guys use the labels, milestones, and assignees, in GitHub to organize issues/pull requests so they can be searched/tracked later. This might be slightly more useful than topic prefixes in the title (e.g. "velo-merge ->"), in the case of labels, and better than trying to find the commits in the git history, in the case of milestones.

---

**Comment by hazendaz** [comment]
I looked over the code and I think we addressed this prior to code being merged back in October.  Feel free to re-open this if this wasn't addressed.
