### ISSUE TITLE
After bdd925b20 plugin lost the ability to run using defaults

### ISSUE THREAD

**Issue by velo** [revelc/formatter-maven-plugin#63]
By reverting bdd925b20  I can run the plugin w/o any eclipse config.xml

If none is found, it does fall back to eclipse default configuration, which is, a good maven CoC practice.

**Comment by velo** [comment]
Fixed at:
https://github.com/revelc/formatter-maven-plugin/pull/64

**Comment by hazendaz** [comment]
That prior commit has a bug plus the entire point was to fix it so it reads resources like jars.  Pretty sure the javascript formatter is broke this way.  We should be able to do both...no settings plus all other options.


Sent by Outlook for Android





On Fri, Aug 7, 2015 at 4:02 PM -0700, "Marvin Froeder" <notifications@github.com> wrote:
Fixed at:
https://github.com/revelc/formatter-maven-plugin/pull/64

---

**Comment by hazendaz** [comment]
Branch revert now exists for this as the original velo-merge was removed as it is in master.  There were notes of merge conflicts so that will need rebased and looked at further.

**Comment by hazendaz** [comment]
Marked as both a bug and enhancement given the changes were to retain original functionality before merge and it's a loss on the other end so it sort of fits both types.

**Comment by velo** [comment]
agreed

**Comment by hazendaz** [comment]
This issue was indirectly resolved as a result of PR #109

**Comment by hazendaz** [comment]
@velo ok maybe this isn't fixed yet entirely.  It no longer fails for missing setup but it actually has nothing to default back too.  The only thing I can think in the code it attempts to do is setting some compilation level items.  However, that section is not reachable code.

I suspect you are referring to this code snippit.  Can you confirm?  If so, should this apply for both java and javascript or everything in general?

```
// TODO Review this as this is not exactly reachable code as file can never be null (ie defaults or spaces)
        Map<String, String> options = new HashMap<>();
        options.put(JavaCore.COMPILER_SOURCE, this.compilerSource);
        options.put(JavaCore.COMPILER_COMPLIANCE, this.compilerCompliance);
        options.put(JavaCore.COMPILER_CODEGEN_TARGET_PLATFORM, this.compilerTargetPlatform);

        return options;
```

**Comment by hazendaz** [comment]
Above code is not reachable.  Reviewed overall code.  That was set in two places.  Both were not reachable.  I have reconfigured this.  I'll open a new ticket regarding this issue.  I'm closing this one.
