### ISSUE TITLE
Whitespace in Javadoc reported

### ISSUE THREAD

**Issue by bennypi** [revelc/formatter-maven-plugin#643]
**Describe the bug**
Trailing whitespace in Javadoc is reported as an error, but neither Eclipse 2022-06 nor the Intellij plugin "EclipseCodeFormatter" remove the whitespace from the JavaDoc. To me this looks like a too strict validation of this formatter.

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Affected version(s) of this project: 2.18.0 and newer
 - OS: Linux Mint 20.3
 - JDK: Azul JDK 11.0.10
 - Maven: 3.8.4
 - Eclipse: 2022-06
 - IntelliJ Plugin EclipseCodeFormatter: 22.0.203.000.0-Eclipse_2021-0

**To Reproduce**
- Checkout the example project https://github.com/bennypi/formatter-test
- Open the project in Eclipse, configure the formatting.xml file for the Eclipse formatter
- Format the single Java file src/main/java/de/bennypi/formatter/test/SimpleClass.java, but Eclipse should not be changing anything
- Run `mvn validate`, this will mark the Java file as not properly formatted.

**Expected behavior**
The plugin's formatter does not complain about the whitespace in the JavaDoc to be consistent with Eclipse's behaviour.

**Comment by bennypi** [comment]
In my opinion this is not a nice user experience. I understand that you want to improve a defect in Eclipse, but this means that using the formatter in Eclipse or IntelliJ does not mean that the files will pass the maven-formatter-plugin. I guess there is no way to exclude whitespace (In Javadoc) for the validate-goal?

**Comment by hazendaz** [comment]
See the javadocs

```
    /**
     * When set to true, remove trailing whitespace on all lines after the formatter has finished.
     * <p>
     * Default to 'true' since 2.18.0
     *
     * @since 2.17.0
     */
    @Parameter(defaultValue = "true", property = "formatter.removeTrailingWhitespace")
    private boolean removeTrailingWhitespace;
```

If you don't want it on, just set that property to ```false```

**Comment by ctubbsii** [comment]
Closing this as answered, since it is already currently possible to tune this feature.
