### ISSUE TITLE
Validate mode - should perform formatting

### ISSUE THREAD

**Issue by hazendaz** [revelc/formatter-maven-plugin#69]
Validate mode fails when formatting possible.  It should format the code as well as that makes it easier to know what to commit prior to submitting.

For reference, latest head will not build on my machine without changing validate to format.  This appears to be line endings issue.

**Comment by velo** [comment]
Validate is meant for CI server.... so it will tell you it is broken.

If you change to format, CI will always tell you the code is fine, even if all classes are single liners =/

**Comment by hazendaz** [comment]
maybe so but that prevents local builds.  It would make more sense I think to have local as format and change it in travis ci so it validates there.  Otherwise, how would I be expected to even run formatting locally?

**Comment by velo** [comment]
not really, if the format is correct it does build locally just fine....

if your local code is not formatted, you need either format on eclipse or use mvn formatter:format

**Comment by hazendaz** [comment]
That's not the behavior I'm after.  Enforce that on travis.  Otherwise it's an unnecessary step fir developers.


Sent by Outlook for Android





On Tue, Sep 8, 2015 at 11:31 PM -0700, "Marvin Froeder" <notifications@github.com> wrote:
not really, if the format is correct it does build locally just fine....

if your local code is not formatted, you need either format on eclipse or use mvn formatter:format

---

**Comment by velo** [comment]
You could have a profile then

**Comment by hazendaz** [comment]
This thread.  I stand behind my points.  This is why forcing at machine level makes no sense.  You are suggesting using the IDE.  All I did tonight, I didn't even have an IDE open.  I did all changes using notepad.  So formatting via eclipse was out of the question.  Anyway, this is fixed on PR #80
