### ISSUE TITLE
Add support for xml-formatter 'deleteBlankLines'

### ISSUE THREAD

**Issue by hazendaz** [revelc/formatter-maven-plugin#692]
Next release of [xml-formatter](https://github.com/revelc/xml-formatter/) will contain new option to 'deleteBlankLines'.  Add support here to provider for that functionality.

**Comment by ctubbsii** [comment]
I got NPEs when I tried to bump to 0.3.0. Something isn't ready.

**Comment by hazendaz** [comment]
Completed with #695
