### ISSUE TITLE
Build fails when running on my machine

### ISSUE THREAD

**Issue by hazendaz** [revelc/formatter-maven-plugin#70]
Possibly due to line endings issue I mentioned on enforced validate.  The build gets this far.

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running net.revelc.code.formatter.support.io.ResourceTest
Tests run: 13, Failures: 6, Errors: 0, Skipped: 0, Time elapsed: 0.026 sec <<< FAILURE! - in net.revelc.code.formatter.s
upport.io.ResourceTest
testAsInputStreamValidDefaultPackageResource(net.revelc.code.formatter.support.io.ResourceTest)  Time elapsed: 0.019 sec
  <<< FAILURE!
org.junit.ComparisonFailure: expected:<alpha[]
]eta> but was:<alpha[
beta>
        at org.junit.Assert.assertEquals(Assert.java:115)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at net.revelc.code.formatter.support.io.ResourceTest.testAsInputStreamValidDefaultPackageResource(ResourceTest.j
ava:73)

testForPath(net.revelc.code.formatter.support.io.ResourceTest)  Time elapsed: 0 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<alpha[]
]eta> but was:<alpha[
beta>
        at org.junit.Assert.assertEquals(Assert.java:115)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at net.revelc.code.formatter.support.io.ResourceTest.testForPath(ResourceTest.java:223)

testAsString(net.revelc.code.formatter.support.io.ResourceTest)  Time elapsed: 0.003 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<alpha subpackage[]
]eta subpackage> but was:<alpha subpackage[
beta subpackage>
        at org.junit.Assert.assertEquals(Assert.java:115)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at net.revelc.code.formatter.support.io.ResourceTest.testAsString(ResourceTest.java:114)

testAsInputStreamValidSubpackageResource(net.revelc.code.formatter.support.io.ResourceTest)  Time elapsed: 0.001 sec  <<
< FAILURE!
org.junit.ComparisonFailure: expected:<alpha subpackage[]
]eta subpackage> but was:<alpha subpackage[
beta subpackage>
        at org.junit.Assert.assertEquals(Assert.java:115)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at net.revelc.code.formatter.support.io.ResourceTest.testAsInputStreamValidSubpackageResource(ResourceTest.java:
89)

testLoadInputStreamClasspath(net.revelc.code.formatter.support.io.ResourceTest)  Time elapsed: 0.001 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<alpha subpackage[]
]eta subpackage> but was:<alpha subpackage[
beta subpackage>
        at org.junit.Assert.assertEquals(Assert.java:115)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at net.revelc.code.formatter.support.io.ResourceTest.testLoadInputStreamClasspath(ResourceTest.java:130)

testLoadInputStreamFile(net.revelc.code.formatter.support.io.ResourceTest)  Time elapsed: 0 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<alpha[]
]eta> but was:<alpha[
beta>
        at org.junit.Assert.assertEquals(Assert.java:115)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at net.revelc.code.formatter.support.io.ResourceTest.testLoadInputStreamFile(ResourceTest.java:146)

Running net.revelc.code.formatter.support.text.TemplateTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 sec - in net.revelc.code.formatter.support.text.Te
mplateTest

Results :

Failed tests:
  ResourceTest.testAsInputStreamValidDefaultPackageResource:73 expected:<alpha[]
]eta> but was:<alpha[
beta>
  ResourceTest.testAsInputStreamValidSubpackageResource:89 expected:<alpha subpackage[]
]eta subpackage> but was:<alpha subpackage[
beta subpackage>
  ResourceTest.testAsString:114 expected:<alpha subpackage[]
]eta subpackage> but was:<alpha subpackage[
beta subpackage>
  ResourceTest.testForPath:223 expected:<alpha[]
]eta> but was:<alpha[
beta>
  ResourceTest.testLoadInputStreamClasspath:130 expected:<alpha subpackage[]
]eta subpackage> but was:<alpha subpackage[
beta subpackage>
  ResourceTest.testLoadInputStreamFile:146 expected:<alpha[]
]eta> but was:<alpha[
beta>

Tests run: 17, Failures: 6, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] parent ............................................. SUCCESS [  6.405 s]
[INFO] formatters ......................................... SUCCESS [  2.412 s]
[INFO] jdt-core ........................................... SUCCESS [ 38.165 s]
[INFO] jsdt-core .......................................... SUCCESS [ 46.219 s]
[INFO] support ............................................ FAILURE [  1.447 s]
[INFO] formatter-maven-plugin ............................. SKIPPED
[INFO] M2E formatter Connector ............................ SKIPPED
[INFO] net.revelc.code.formatter .......................... SKIPPED
[INFO] net.revelc.code.formatter.feature .................. SKIPPED
[INFO] net.revelc.code.formatter.site ..................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE

**Comment by hazendaz** [comment]
This must be windows related.  It's otherwise working on travis ci

**Comment by velo** [comment]
Appvevoy is windows...
https://ci.appveyor.com/project/velo/formatter-maven-plugin/history

Last 2 builds are broken...

**Comment by hazendaz** [comment]
Hmmmm.  Pull request I merged took forever on that part then showed green.  Didn't know what that tool was but glad to know about it and shows same issue.  I wonder though if it's setup only to show green on completion thus false assumption of it working.  At least a place to start looking.  Thanks for pointing this out.  I'll look a bit tonight.


Sent by Outlook for Android





On Tue, Sep 8, 2015 at 11:27 PM -0700, "Marvin Froeder" <notifications@github.com> wrote:
Appvevoy is windows...
https://ci.appveyor.com/project/velo/formatter-maven-plugin/history

Last 2 builds are broken...

---

**Comment by hazendaz** [comment]
Fixed on my machine by using system line endings.  This presumably will work on both travis and app voyer.  I'm pushing up shortly once my full build finishes.

**Comment by hazendaz** [comment]
Build was failing on appvoyer as well for same reason.  It's been fixed now.  The test logic was specific on \n rather than being able to run on machines set with other line ending styles.  gitattributes already handled correctly but now appvoyer is doubly set with both it's build config as well as the gitattributes to be completely sure.  Both ways were watched on multiple builds without issue.
