### ISSUE TITLE
Large whitespace in debug output 

### ISSUE THREAD

**Issue by delanym** [revelc/formatter-maven-plugin#713]
The debug output includes large blocks of whitespace.

`mvn formatter:format -X -l output`

Maven v3.9.0, formatter-maven-plugin v2.22.0

``` log
[DEBUG]   New match='profiles/profile/setting'
[DEBUG]   Fire begin() for ObjectCreateRule[className=net.revelc.code.formatter.model.Setting, attributeName=null]
[DEBUG] [ObjectCreateRule]{profiles/profile/setting} New 'net.revelc.code.formatter.model.Setting' using default empty constructor
[DEBUG]   Fire begin() for SetNextRule[methodName=addSetting, paramType=null, paramTypeName=null, useExactMatch=false, fireOnBegin=false]
[DEBUG]   Fire begin() for SetPropertiesRule[aliases={id=id}, ignoreMissingProperty=true]
[DEBUG] [SetPropertiesRule]{profiles/profile/setting} Setting property 'id' to 'id'
[DEBUG] [SetPropertiesRule]{profiles/profile/setting} Setting property 'value' to 'value'
[DEBUG] [SetPropertiesRule]{profiles/profile/setting} Set 'net.revelc.code.formatter.model.Setting' properties
[DEBUG] BeanUtils.populate(net.revelc.code.formatter.model.Setting@7940cd5e, {id=org.eclipse.wst.jsdt.core.formatter.insert_new_line_before_while_in_do_statement, value=do not insert})
[DEBUG] Convert string 'org.eclipse.wst.jsdt.core.formatter.insert_new_line_before_while_in_do_statement' to class 'java.lang.String'
[DEBUG] Converting 'String' value 'org.eclipse.wst.jsdt.core.formatter.insert_new_line_before_while_in_do_statement' to type 'String'
[DEBUG] Convert string 'do not insert' to class 'java.lang.String'
[DEBUG] Converting 'String' value 'do not insert' to type 'String'
[DEBUG]   Fire begin() for SetPropertiesRule[aliases={value=value}, ignoreMissingProperty=true]
[DEBUG] [SetPropertiesRule]{profiles/profile/setting} Setting property 'id' to 'id'
[DEBUG] [SetPropertiesRule]{profiles/profile/setting} Setting property 'value' to 'value'
[DEBUG] [SetPropertiesRule]{profiles/profile/setting} Set 'net.revelc.code.formatter.model.Setting' properties
[DEBUG] BeanUtils.populate(net.revelc.code.formatter.model.Setting@7940cd5e, {id=org.eclipse.wst.jsdt.core.formatter.insert_new_line_before_while_in_do_statement, value=do not insert})
[DEBUG] Convert string 'org.eclipse.wst.jsdt.core.formatter.insert_new_line_before_while_in_do_statement' to class 'java.lang.String'
[DEBUG] Converting 'String' value 'org.eclipse.wst.jsdt.core.formatter.insert_new_line_before_while_in_do_statement' to type 'String'
[DEBUG] Convert string 'do not insert' to class 'java.lang.String'
[DEBUG] Converting 'String' value 'do not insert' to type 'String'
[DEBUG] endElement(,,setting)
[DEBUG]   match='profiles/profile/setting'
[DEBUG]   bodyText=''
[DEBUG]   Fire body() for ObjectCreateRule[className=net.revelc.code.formatter.model.Setting, attributeName=null]
[DEBUG]   Fire body() for SetNextRule[methodName=addSetting, paramType=null, paramTypeName=null, useExactMatch=false, fireOnBegin=false]
[DEBUG]   Fire body() for SetPropertiesRule[aliases={id=id}, ignoreMissingProperty=true]
[DEBUG]   Fire body() for SetPropertiesRule[aliases={value=value}, ignoreMissingProperty=true]
[DEBUG]   Popping body text '























































































'
[DEBUG]   Fire end() for SetPropertiesRule[aliases={value=value}, ignoreMissingProperty=true]
[DEBUG]   Fire end() for SetPropertiesRule[aliases={id=id}, ignoreMissingProperty=true]
[DEBUG]   Fire end() for SetNextRule[methodName=addSetting, paramType=null, paramTypeName=null, useExactMatch=false, fireOnBegin=false]
[DEBUG] [SetNextRule]{profiles/profile/setting} Call net.revelc.code.formatter.model.Profile.addSetting(net.revelc.code.formatter.model.Setting@7940cd5e)
[DEBUG]   Fire end() for ObjectCreateRule[className=net.revelc.code.formatter.model.Setting, attributeName=null]
[DEBUG] [ObjectCreateRule]{profiles/profile/setting} Pop 'net.revelc.code.formatter.model.Setting'
[DEBUG] characters(
)
[DEBUG] startElement(,,setting)
[DEBUG]   Pushing body text '
























































































'
```

**Comment by delanym** [comment]
```
git clone --branch issue-713 https://github.com/delanym/formatter-maven-plugin.git
cd formatter-maven-plugin
./do
```

**Comment by ctubbsii** [comment]
These debug messages are not coming from this plugin. They seem to be coming from Maven, as it parses the configuration. I don't know why it's happening, but I don't think it's an issue for this plugin to solve.

**Comment by delanym** [comment]
Seems an issue with commons-digester3: https://issues.apache.org/jira/browse/MNG-7747

**Comment by hazendaz** [comment]
Likely coming from our usage of it here https://github.com/revelc/formatter-maven-plugin/blob/main/src/main/java/net/revelc/code/formatter/model/ConfigReader.java

So it seems unless I'm reading that wrong as I only quickly looked is that its doing a quick configuration it can read the xml file.  Maybe we can do that some other way.

**Comment by hazendaz** [comment]
But yes, not maven, its that library which I know tomcat uses it and its incredibly noisy in debug in general.  Still nothing we can do in regards to what is going on there I don't think.  The code is certainly probably really old here.  I probably did an upgrade from the old commons digester to latest but didn't even remember we use that.

**Comment by ctubbsii** [comment]
Oh, my mistake. When I saw that it seemed to be parsing Maven configuration, it seemed like Maven was responsible. But, I guess we're using it. Still, like @hazendaz said, I'm not sure there's anything we can do about it... the debug logs are going to be noisy. If there's a bug in the logs from the digester library, I suggest filing a report with the commons-digester3 maintainers. We can upgrade to the newer version if they release one that fixes it. We can also look into alternatives for reading the config file, but I'm not sure we have a compelling reason to do so. Noisy or poorly-formatted debug lines aren't really very compelling reasons, I think.

**Comment by ctubbsii** [comment]
It's a bit hard to troubleshoot how this config parsing code is being used, because it's a bit convoluted, and there's a bit of an overuse of the `var` keyword, obscuring the types everywhere, but I'm looking into it a bit, to see if there's an easy way to use something else, or strip this out entirely.

**Comment by ctubbsii** [comment]
After spending some time figuring out how we're using digester, I think it's best that we leave it as-is. It's possible we could switch to something like FasterXML's Jackson, which I'm more familiar with, but it would require rewriting the models, and the way it is currently implemented is pretty lightweight, has good validation for edge cases (like having multiple profiles in the XML file), and works for both the Java and the Javascript formatter config files. My recommendation is to leave it alone and maybe file a bug with upstream digester maintainers if the whitespace in the debug output is too annoying.
