### ISSUE TITLE
NOTICE: Eclipse 2023-06 Requires jdk 17 for many parts

### ISSUE THREAD

**Issue by hazendaz** [revelc/formatter-maven-plugin#758]
unless Eclipse actually fixed issues present with mockito which is possible with 2023-06, I'd like to propose we stay where we are for a while.  Jdk 17 is now required on many of the components which is making it too restrictive to use and cutting too much of our community out.  I think we should wait until early 2024 before we force jdk 17 on our users.

**Comment by ctubbsii** [comment]
Whenever you say Eclipse has outstanding issues relevant to an issue here, I think it would be helpful if you provided a reference, so that others can follow, or at least understand, what you're referring to.

**Comment by ctubbsii** [comment]
> I think we should wait until early 2024 before we force jdk 17 on our users.

Given that it would merely be a build requirement, users can just change their build JDK and use `-release` (`maven.compiler.release`) for their own projects. They can also just choose to use the older releases of this plugin. We could bump the major version here to make that delineation more clear. I think it wouldn't be so bad if we did that prior to 2024. We could still do bugfix releases on the current major version if it were necessary.

**Comment by hazendaz** [comment]
Assume the eclipse bug.  See https://github.com/revelc/formatter-maven-plugin/issues/712 where I documented the issue a while back with suspected links on the code they broke it with.  I haven't looked since at nothing indicates they fixed the issue.

The jump Eclipse is forcing to jdk 17 I'm aware of as I have renovate on the my fork and eclipse did not uniformly do jdk 17.  The binaries were released yesterday and for other repos in mass I won't be taking any part of heavy-handed jump as it will kill too many projects.   Its half mixed with 11.  Their track record for last year plus is documented all over and rather poor as it's been a constant break to everyone.  I build eclipse with plugins for my firm and have not been able to release for a year as it's one thing after another.  Various plugins have raised issues consistently with poor documentation and sweeping breaking changes.  2023-06 is almost entirely just a security based release so half the code forcing jdk 17 seems unnecessary.

Its also documented on large threads from products such as maven about jdk 17 hardline being too much fir many.  Regardless of release tag not all can get there. It's not that simple.  I've got users still stuck on java 8.  I've got 100s stuck on 11.  It's already a struggle to get teams to use the formatter even in my role.  If we force to 17 just because eclipse did with little functional value to improved formatting other that to the very few using records class and newer switch statements, it's not a question our user base will just drop.



Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ctubbsii** [comment]
Well, I'm fine with holding back, I guess. As long as formatting is working, we don't really need to do any new releases. The main reason we need to release is to get formatting support for newer Java versions, though. The current formatter supports formatting Java 17 code, so that's fine. We can see what demand there is for formatting code newer than that, and what support Eclipse has or doesn't have for that.

As for the Eclipse issues... I'm still not sure I understand what specifically is broken. Your phrasing on the linked issue did not describe the issue very clearly. Is this just a "some tabs aren't converted to spaces" bug? Or is it more than that?

**Comment by hazendaz** [comment]
The issue is due to usage of static import on mockito 'when'. The "Handle 'when' clause in switch pattern expressions" https://github.com/eclipse-jdt/eclipse.jdt.core/commit/ebc978ee6a29e02681d1f360bc47be314e8a7cae that I noted earlier is the issue. I do not know if they fixed it but any fix requires we move to jdk 17. So it would be best to drop back actually.

**Comment by hazendaz** [comment]
Issue with formatter is reported but not fixed https://github.com/eclipse-jdt/eclipse.jdt.core/issues/609

A number of other recent issues are also on their board.

**Comment by hazendaz** [comment]
closing as we will require java 17 now.
