### ISSUE TITLE
problem with multi-module project 

### ISSUE THREAD

**Issue by danyaljj** [revelc/formatter-maven-plugin#84]
There is a solution [here](http://code.revelc.net/formatter-maven-plugin/examples.html#Custom_Configuration_File) for handling multi-module projects, by creating an additional module `build-tools`. I was wondering if it is possible to bypass creating this extra module and just add the config file to one of the existing modules. Essentially is it possible to have the following structure for the project? 
```
|-- pom.xml
|-- moduleA
|   |-- src
|   |   `-- main
|   |       `-- resources
|   |           `-- eclipse
|   |               `-- formatter.xml
|   `-- pom.xml
|-- moduleB
```
And modify the plugin definition to the following: 
```
<project>
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.googlecode.example.multiproject</groupId>
  <artifactId>multiproject-parent</artifactId>
  <version>1.0</version>
  <packaging>pom</packaging>
  <name>Multiproject Parent</name>
  <build>
    <plugins>
      <plugin>
        <groupId>net.revelc.code</groupId>
        <artifactId>formatter-maven-plugin</artifactId>
        <version>0.5.3-SNAPSHOT</version>
        <executions>
          <execution>
            <goals>
              <goal>format</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <configFile>eclipse/formatter.xml</configFile>
        </configuration>
        <dependencies>
          <dependency>
            <groupId>com.googlecode.example.multiproject</groupId>
            <artifactId>moduleA</artifactId>
            <version>1.0</version>
          </dependency>
        </dependencies>
      </plugin>
    </plugins>
  </build>
  <modules>
    <module>moduleA</module>
    <module>moduleB</module>
  </modules>
</project>
```

When I tried this I got some issues with the definition of the `dependency` for the plugin.

**Comment by ctubbsii** [comment]
I just put the following in my parent:
```xml
    <eclipseFormatterStyle>${project.parent.basedir}/contrib/style.xml</eclipseFormatterStyle>
```
```xml
          <plugin>
            <groupId>com.googlecode.maven-java-formatter-plugin</groupId>
            <artifactId>maven-java-formatter-plugin</artifactId>
            <configuration>
              <configFile>${eclipseFormatterStyle}</configFile>
            </configuration>
          </plugin>
```
And, for any child modules deeper than 1 level, I just override ```${eclipseFormatterStyle}``` appropriately.

**Comment by danyaljj** [comment]
Just to make sure I understand it correctly: by "And, for any child modules deeper than 1 level, I just override ..." you mean you add this definition to `pom.xml` of each module? 
Do you have an example project doing this?

**Comment by ctubbsii** [comment]
Hmm, actually... it looks like I don't override... I have all my modules inheriting from the same parent, so that line works for all of them. The Apache Accumulo project does this: https://github.com/apache/accumulo/blob/master/pom.xml#L129

**Comment by velo** [comment]
Or, you make formatter plugin run only once by setting inheritance to false
https://maven.apache.org/guides/mini/guide-configuring-plugins.html#Using_the_inherited_Tag_In_Build_Plugins

**Comment by danyaljj** [comment]
It worked! Great! 
A side question: when I run `mvn formatter:format` it shows me:
```
[INFO] --- formatter-maven-plugin:0.5.2:format (default-cli) @ illinois-edison ---
[INFO] Using 'UTF-8' encoding to format source files.
[INFO] Number of files to be formatted: 102
[INFO] Successfully formatted: 0 file(s)
[INFO] Fail to format        : 0 file(s)
[INFO] Skipped               : 102 file(s)
[INFO] Approximate time taken: 0s
```
Does "skipped" refer to the files that are already formatted?

**Comment by ctubbsii** [comment]
Yes, skipped refers to files that are already formatted.
