### ISSUE TITLE
Changing the size of the indentaton

### ISSUE THREAD

**Issue by danyaljj** [revelc/formatter-maven-plugin#85]
So I got the Google java style from here:
https://github.com/google/styleguide/blob/gh-pages/eclipse-java-google-style.xml

And added to the formatter plugin. The outputs seemed like it is doing 2-space indentation. But I want 4-space indentation. I think I found the like which controls the indentation: 
```
<setting id="org.eclipse.jdt.core.formatter.continuation_indentation" value="2"/>
```
Changed to: 
```
<setting id="org.eclipse.jdt.core.formatter.continuation_indentation" value="4"/>
```
Ran the `formatter:format` again, but nothing changed. Am I doing something wrong?

**Comment by hazendaz** [comment]
There is another setting you will also need to set to 4.  That one is for line continuation.  The other will control the rest.  I forget the element name offhand.


Sent by Outlook for Android





On Tue, Nov 10, 2015 at 5:00 PM -0800, "Daniel Khashabi" <notifications@github.com> wrote:
So I got the Google java style from here:
https://github.com/google/styleguide/blob/gh-pages/eclipse-java-google-style.xml

And added to the formatter plugin. The outputs seemed like it is doing 2-space indentation. But I want 4-space indentation. I think I found the like which controls the indentation:
```
<setting id="org.eclipse.jdt.core.formatter.continuation_indentation" value="2"/>
```
Changed to:
```
<setting id="org.eclipse.jdt.core.formatter.continuation_indentation" value="4"/>
```
Ran the `formatter:format` again, but nothing changed. Am I doing something wrong?

---
Reply to this email directly or view it on GitHub:
https://github.com/revelc/formatter-maven-plugin/issues/85

**Comment by hazendaz** [comment]
@ danyaljj 

This is the settings you need to enforce 4 spaces when using googles rules.

<setting id="org.eclipse.jdt.core.formatter.tabulation.size" value="4"/>

They have that set to 2.  Try that, if it doesn't work, you could look at my build tools project which contains both 2 character and 4 character files for use.  The 'build tools' works with 0.5.2 version of this code base.  If you have any further issue, please feel free to re-open this.

<dependency>
    <groupId>com.github.hazendaz</groupId>
    <artifactId>build-tools</artifactId>
    <version>1.1.2</version>
</dependency>
