### ISSUE TITLE
Formatter no longer formats in version 2.24.0

### ISSUE THREAD

**Issue by delanym** [revelc/formatter-maven-plugin#894]
With version 2.23.0 of the plugin if I had the code `var result =  function.apply(input);` the formatter would correct the double space based on what I believe was this eclipse rule
```xml
<setting id="org.eclipse.jdt.core.formatter.insert_space_after_assignment_operator" value="insert"/>
``` 
Then when the checkstyle plugin executed further in the lifecycle the rule
https://checkstyle.sourceforge.io/checks/whitespace/singlespaceseparator.html
would pass.

When we migrated to Java 21 I had to disable the formatter, and also checkstyle.
With version 2.24.0 of the formatter plugin I reactivated both of these plugins, and now checkstyle is catching the double space.
Why is the formatter not formatting the code? I have confirmed it is being invoked.
Do I need to update the custom eclipse formatting xml?

I checked the plugin documentation (https://code.revelc.net/formatter-maven-plugin/examples.html#setting-compiler-version which I see is out of date, as is the homepage readme https://github.com/revelc/formatter-maven-plugin/blob/main/README.md)
I added the last three configurations items just in case, but it makes no difference
```xml
<configuration>
            <encoding>UTF-8</encoding>
            <configFile>eclipse/formatter.xml</configFile>
            <skipCssFormatting>true</skipCssFormatting>
            <skipFormatting>false</skipFormatting>
            <skipHtmlFormatting>true</skipHtmlFormatting>
            <skipJavaFormatting>false</skipJavaFormatting>
            <skipJsFormatting>true</skipJsFormatting>
            <skipJsonFormatting>true</skipJsonFormatting>
            <skipXmlFormatting>true</skipXmlFormatting>
            <compilerSource>${maven.compiler.release}</compilerSource>
            <compilerCompliance>${maven.compiler.release}</compilerCompliance>
            <compilerTargetPlatform>${maven.compiler.release}</compilerTargetPlatform>
          </configuration>
```

**Comment by jamezp** [comment]
I think I found the fix for this. It seems to fail if you run the `validate` goal, but only if the there is no cache. I'm testing the fix locally now, then I'll send up a PR.

**Comment by jamezp** [comment]
#896 should fix this

**Comment by hazendaz** [comment]
Nice catch.  I will get a release out sometime tomorrow on this.  As a bonus, javaparser just released full java 21 support today, so that will help here too, and I'll release the import plugin as well for the same reason.

I do want to possibly rewrite the problematic method here, if possible, as clearly a partial copy-paste issue that could have been avoided as well as tests correctly didn't catch it.  I didn't check the diff but believe based on the fix that was all part of the most current release fixing all formatter config types in the hashing.  I'll review in more depth before releasing again.

Thanks!

**Comment by hazendaz** [comment]
ok looked at overall diff, it was copy-paste as I figured on that part.  As soon as @jamezp gets restored portion of code counts back to how it was originally, this can be resolved.  I want to look more at the counts we have though as it seems looking through there we are trying to assume 2 things with one of them and it may not be super accurate or clear thus change made during the fix.  I also want to shore up some of that code once the patch is applied later today so this is unlikely to occur again.  I plan to get this released tonight as 2.24.1.

**Comment by jamezp** [comment]
I've updated the @hazendaz. Thank you!

**Comment by hazendaz** [comment]
ok our integration tests are pretty weak here.  I'm cleaning up the code but won't have time to try to add a validate only test and think we need quite a bit more in that area.  I'll try to circle back later.  If anyone has some time to introduce some integration tests that would be great.  That is how this didn't get caught as the normal code calls directly so caching isn't involved on those calls and the formatting worked there.  I'll have a PR in a few though that at least uses same code method to process the hash calculation so its not so repetitive and harder to mess up.

**Comment by hazendaz** [comment]
@jamezp @delanym Released 2.24.1, can you give it a try and let me know if its working well now?

note on javaparser I mentioned.  That was only for impsort (sorry to note it here).  I'll get that released out tomorrow as I think same audience was after changes there.  Ran out of time today.

**Comment by delanym** [comment]
Thank goodness its working again. So many issues crept in already - what would I do without this plugin?

**Comment by jamezp** [comment]
This also works for me! Thank you for the quick turnaround @hazendaz.

**Comment by hazendaz** [comment]
Perfect! Thanks all for confirming.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
