### ISSUE TITLE
Can you tell me the maven repository for all versions of the plugin?

### ISSUE THREAD

**Issue by jerryag** [revelc/formatter-maven-plugin#90]
I´m using The IDE Eclipse Mars (4.5.0) with the format source feature turned on in the Save Actions. And I use the formatter-maven-plugin 0.5.2 (found in maven central repository) to format all my java source code on Build. But sometimes the plugin formats the code in different way from Eclipse.
In the home page of project there is a table "Eclipse Compatibility" where is shown the version 2.0.0 of plugin is the compatible version for my IDE.

But I can´t find this version 2.0.0 of plugin in any maven public repository. 

Can you tell me the maven repository for all versions of the plugin?

Thanks in advance.

**Comment by ctubbsii** [comment]
The README you refer to is in the master branch, which is under development. Not all versions it describes have yet been released. Some are still in progress. But, once complete, they will be Maven Central. You can check the tags in this repo to see a released/tagged version. All tagged versions should be in Maven Central. However, keep in mind, that this project has migrated from an older one, so the groupId has changed: check the pom.xml in the tag to identify the proper maven coordinates to look for in Maven Central.
