### ISSUE TITLE
[site] incorrect usage artifact

### ISSUE THREAD

**Issue by glelouet** [revelc/formatter-maven-plugin#93]
the usage example uses 

> 
>       <plugin>
>         <groupId>com.googlecode.maven-java-formatter-plugin</groupId>
>         <artifactId>maven-java-formatter-plugin</artifactId>

which is the old plugin you forked from

**Comment by glelouet** [comment]
http://code.revelc.net/formatter-maven-plugin/usage.html#

**Comment by hazendaz** [comment]
Can you submit a pull request to fix this?


Sent from Outlook Mobile






On Tue, Feb 2, 2016 at 1:29 AM -0800, "glelouet" <notifications@github.com> wrote:





http://code.revelc.net/formatter-maven-plugin/usage.html#

---

**Comment by hazendaz** [comment]
This is fixed in the code base.  We haven't pushed a site in some time.  Closing as we get closer to releasing.
